/* GENERATED by toolkit/clientscan/movehook/gensites.py -- DO NOT EDIT.
 *
 * Source of truth: content/movecode.toml, whose rows carry their own
 * provenance and are checked by content.py. Owner's ruling PLAN.md §7 Q12(a).
 * Every first byte below was re-read from the pinned client and matched.
 * Verified against: 2026-07-29_221c13772c7a
 */
#ifndef MOVEHOOK_SITES_H
#define MOVEHOOK_SITES_H

/* THE SHAPES THE HANDLER EMULATES. Every site's byte was re-read from the
 * pinned client and matched against ITS OWN shape's byte before this file
 * was written; a byte outside its shape stops generation. Two shapes, not
 * one free-for-all: an entry row that decayed into a ret is still caught.
 * See PLAN.md §7 Q12(d) and content/movecode.toml's ret block. */
#define SHAPE_ENTRY 0u   /* 0x55 push ebp -> esp -= 4; [esp] = ebp; eip = a+1 */
#define SHAPE_RET   1u   /* 0xC3 ret      -> eip = [esp]; esp += 4           */

#define NSITES 19u

typedef struct {
    unsigned long rva;
    const char   *name;
    int           deref_agent;   /* is ecx an agent pointer at entry? */
    int           deref_a;       /* arg index (1-6) to deref as a point, 0=none */
    int           deref_b;
    int           deref_agent_arg; /* arg index holding a SECOND agent, 0=none */
    int           deref_fence;   /* read AgTrack's per-agent clientControlled */
    unsigned      stride;        /* store 1 hit in N; 0/1 = every hit. The
                                    HIT COUNT is unaffected and is what the
                                    sidecar reports, so a strided site still
                                    gives an exact denominator -- see the
                                    note at the stride test in movehook.c. */
    int           deref_out;     /* arg index of `int* outCount`, 0=none */
    int           deref_out_path;/* arg index of `point* outPath`, 0=none */
    unsigned      shape;         /* SHAPE_ENTRY or SHAPE_RET -- selects which
                                    ONE instruction the handler re-emulates. */
} site_t;

/* rva, name, deref_agent, deref_a, deref_b, deref_agent_arg, deref_fence,
 * stride, deref_out, deref_out_path, shape */
static const site_t SITES[NSITES] = {
    { 0x001FC7A0u, "agapi_setdest", 0, 2, 0, 0, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x005FC7A0 */
    { 0x00205FC0u, "agtrack", 0, 0, 0, 1, 1, 0u, 0, 0, SHAPE_ENTRY },   /* 0x00605FC0 */
    { 0x001FE950u, "bake", 1, 0, 0, 0, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x005FE950 */
    { 0x0041B580u, "chcli_advance", 0, 0, 0, 0, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x0081B580 */
    { 0x0041A8F0u, "chcli_dir", 0, 0, 0, 0, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x0081A8F0 */
    { 0x0041ADB0u, "chcli_point", 0, 0, 0, 0, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x0081ADB0 */
    { 0x00309E90u, "mapfindpath", 0, 1, 2, 0, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x00709E90 */
    { 0x00309F0Fu, "mapfindpath_ret1", 0, 1, 0, 0, 0, 0u, 5, 6, SHAPE_RET   },   /* 0x00709F0F */
    { 0x00309F44u, "mapfindpath_ret2", 0, 1, 0, 0, 0, 0u, 5, 6, SHAPE_RET   },   /* 0x00709F44 */
    { 0x0030A0ADu, "mapfindpath_ret3", 0, 1, 0, 0, 0, 0u, 5, 6, SHAPE_RET   },   /* 0x0070A0AD */
    { 0x0030A0D4u, "mapfindpath_ret4", 0, 1, 0, 0, 0, 0u, 5, 6, SHAPE_RET   },   /* 0x0070A0D4 */
    { 0x002022B0u, "reseed", 1, 0, 0, 1, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x006022B0 */
    { 0x00205E40u, "resync", 0, 0, 0, 0, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x00605E40 */
    { 0x00202B20u, "setposition", 1, 1, 0, 0, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x00602B20 */
    { 0x00202A40u, "setter", 1, 0, 0, 0, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x00602A40 */
    { 0x002055E0u, "snaptest", 0, 0, 0, 2, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x006055E0 */
    { 0x001FEF70u, "stepclear", 0, 0, 0, 0, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x005FEF70 */
    { 0x002020B0u, "teleport", 1, 0, 0, 0, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x006020B0 */
    { 0x00200140u, "tick", 1, 0, 0, 0, 0, 0u, 0, 0, SHAPE_ENTRY },   /* 0x00600140 */
};

/* Agent struct offsets the handler reads at each hit. */
#define A_FACING               0xC4u   /* facing */
#define A_FLAGS                0x20u   /* m_flags */
#define A_ID                   0x10u   /* agent id */
#define A_POINT                0x78u   /* m_point */
#define A_POINT_TIME           0x58u   /* timestamp of m_point */
#define A_SEGMENT_POINT        0x88u   /* m_segmentPoint */
#define A_SEQ                  0x50u   /* move sequence / queued timer handle */
#define A_TARGET_POINT         0x9Cu   /* m_targetPoint */
#define A_TIME_STOP_MOVEMENT   0x48u   /* m_timeStopMovement */
#define A_VELOCITY             0xB0u   /* velocity x, y */
#define A_WORLD                0x24u   /* m_world */
#define A_X98                  0x98u   /* unnamed scalar */

#endif /* MOVEHOOK_SITES_H */
