"""Assemble a whole Bloated map file from typed parameters.

`mapfile.py` proved the container round-trips (698 of 698). `terrain.py` and
`pathchunk.py` proved their chunks do (349 of 349 each). This module is the
authoring direction of all three: it takes **numbers** -- dims, a height field, a
tile table, a navmesh, a world rect -- and emits a complete `ffna` type-3 map
payload the client's own loader rules accept.

    with Archive() as ar:
        mf, rep = build_like(46196, ar)      # row 46196, from its parameters
        assert mf.encode() == ar.read(row)   # BYTE-IDENTICAL, 8,471 bytes
        print(rep.summary())                 # and what was generated vs carried

    mf, rep = build_flat(64, 64, height=-1000.0, archive=ar)   # from nothing

**BYTE-IDENTITY IS HALF A RESULT AND THE WEAKER HALF.** A program that copies
8,471 bytes passes it, and the licensing constraint below makes a copying builder
the *expected* shape for part of the file. So every build returns a `BuildReport`
that says, per chunk, whether the bytes were GENERATED by our encoders from typed
values or CARRIED verbatim out of the archive, and the carried ones are named
individually rather than lumped. Read `rep.summary()`, not just the equality.

MEASURED on row 46196 (`vault/dat_study/Gw.dat`, 2026-08-11), 8,471 bytes:

    generated  7,814 B  92.24%   framing 149, Terrain 7,165, Path 419,
                                 Map Parameters 41, Dependencies 40
    carried      657 B   7.76%   Props 51, Zones 42, Mission 69,
                                 Environment 178, Light 7, Shore 17,
                                 Sight 44, Sound 17            (425 B, 8 kinds)
                                 + the five FINDINGS 14 constants      (232 B)

The brief for this rung predicted ~93.4%; the 1.2-point shortfall is the Header
(8 B) and the Water Dependencies chunk (197 B), both of which this module carries
rather than generates because `FINDINGS 14` names them among the five constants
that may not enter the repo. Generating the Header instead -- FINDINGS 17.5 says the
client's own code writes exactly `{u32 0x39871124, u32 3}`, so we could -- moves
the figure to 92.34%. Nothing in the rung hangs on either decision, and carrying
is the conservative direction.

**A STRICTER NUMBER, because the headline flatters the terrain chunk.** Of those
7,165 generated terrain bytes, 2,312 reach `terrain.py`'s encoder as `bytes`
objects it emits without transforming (tiles 1,024, shade 1,024, tag 3's bit
field 256, the two 4-byte tile tables). `mapfile.byte_census` counts those as
carried and so does `BuildReport.strict_generated`: **5,502 B, 64.95%** on
`build_like`. On `build_flat` the same arrays are produced from scalars this
module was handed, so they are not ArenaNet bytes at all -- which is exactly why
the split is reported per build and not stated once as a property of the format.

THE PROVENANCE CONSTRAINT IS THE DESIGN, not a caveat on it. `FINDINGS 14`:
five mandatory chunks are byte-identical ArenaNet constants across all 349 maps
-- `0x20000000` (8 B), `0x2000000A` (13 B), `0x2000000E` (9 B), `0x20000006`
(5 B) and `0x21000006` (197 B), 232 bytes per map. `CLAUDE.md`'s provenance gate
says zero ArenaNet bytes in the repo, ever, and that it is not retrofittable. So
those 232 bytes are **read from the owner's own archive at run time** and this
module REFUSES to build without one (`NoConstants`). They are never stored here:
not as files, not as hex literals, not as base64, not in a test fixture --
`test_mapbuild.py` reads them from the vault too and skips when it cannot.

The donor is deliberately **not** the map being rebuilt, by default. FINDINGS 14's
claim is that these five are constant across the corpus; reading them out of a
different map and still landing byte-identical on row 46196 is a check that can
fail, and reading them out of row 46196 itself is not one.

**AND ONE OF THE FIVE IS NOT CONSTANT.** MEASURED here, 2026-08-11, over a
sample of 12 maps: `0x20000000`, `0x2000000A`, `0x2000000E` and `0x21000006` are
byte-identical on 12 of 12, and `0x20000006` (Water) takes **two** values --
3 maps carry one, 9 carry the other, and they differ in exactly one byte of the
five (FINDINGS 3 reads that chunk as a u32 and a flag; the values themselves stay
in the archive, which is why they are described and not quoted here).
FINDINGS 14 says as much in a parenthesis ("5 B, two
values") and the first version of this module trusted the sentence rather than
the parenthesis; row 46196 and row 7982 both happened to agree with their donors
and it round-tripped anyway, which is exactly the shape of a bug that ships. So
`build_like` VERIFIES each borrowed constant against the map it is rebuilding,
substitutes that map's own bytes where they differ, and NAMES the substitution in
the report. Four of the five are corpus constants and the report says which.

WHAT "GENERATED" MEANS HERE, precisely, because the word does a lot of work:

  * the bytes were emitted by our encoders from typed values, with every size
    and count re-derived at encode time (`mapfile` re-derives the chunk table's
    `size`; `terrain` and `pathchunk` re-derive every record size and count);
  * for `build_like` the VALUES came from the source map -- that is what "like"
    means, and it is how a specific map gets reproduced;
  * for `build_flat` the values came from the caller's arguments and nothing
    else.

Generated does NOT mean "understood". Seventeen chunk kinds are still carried
opaquely and each is a rung of its own; the report names them so that stays
visible.

THE CHUNK ORDER IS THE FILE'S, NOT A CANONICAL ONE. FINDINGS 3 measured a
single total order across the corpus (321 ordered pairs, 0 contradictory), but
`build_like` reproduces the source's own order and `build_flat` takes an order
that must be a subsequence of a reference the caller supplies -- measured at run
time from a real map, never a list typed in here.

SCOPE. Nothing here opens a file for writing and nothing places bytes in an
archive -- that is `datplan.py` and `datwrite.py`. The CLI's `--out` writes a
built payload to disk and REFUSES any path inside the working tree, because a
`build_like` output is derived ArenaNet data.

UNVERIFIED against a client: nothing built here has been loaded. `gates()`
reproduces every open-time rule FINDINGS 17.4/17.5 states, and its control is
that a shipped retail map must pass all of them -- a gate a real map fails is our
bug, not the map's.

    python toolkit/mapdata/mapbuild.py                    # row 46196, reported
    python toolkit/mapdata/mapbuild.py --row 46196 --verbose
    python toolkit/mapdata/mapbuild.py --flat 64x64
    python toolkit/mapdata/mapbuild.py --flat 32x32 --out <path outside the repo>
"""

import argparse
import os
import struct
import sys
import uuid as uuidlib

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
import vaultpath                                            # noqa: E402
from archive import Archive, DEFAULT_DAT, file_id_table     # noqa: E402
import mapchunks                                            # noqa: E402
from mapchunks import MapIndex, chunk_label, decompose      # noqa: E402
import mapfile                                              # noqa: E402
from mapfile import (MapFile, Chunk, FORM_TERRAIN, FORM_DEPENDENCIES,  # noqa: E402
                     FORM_OPAQUE, CHUNK_HEADER, FFNA_HEADER_LEN,
                     MAP_FFNA_TYPE)
import pathchunk                                            # noqa: E402
from pathchunk import PathChunk, PATHING_CHUNK              # noqa: E402
import terrain as terrainmod                                # noqa: E402
from terrain import (Terrain, ShadowBlock, TERRAIN_CHUNK, CELL_PITCH,  # noqa: E402
                     CHUNK_SIZE, CHUNK_PITCH, MAX_CELLS, SEQUENCE_SHORT,
                     SEQUENCE_LONG)
import trnshadow                                            # noqa: E402

# Two dirnames from this file names `toolkit/`; three names the repo root. The
# same off-by-one shipped broken in `mapexport.py` and wrote 745 KB of derived
# ArenaNet bytes into the working tree, so it is spelled out and tested.
REPO_ROOT = os.path.dirname(os.path.dirname(HERE))

# ------------------------------------------------------------- the chunk ids

HEADER_CHUNK = 0x20000000
WATER_CHUNK = 0x20000006
LOCATIONS_CHUNK = 0x2000000A
MAP_PARAMS_CHUNK = 0x2000000C
COLLISION_CHUNK = 0x2000000E
WATER_DEPS_CHUNK = 0x21000006

# FINDINGS 14: byte-identical ArenaNet constants in all 349 maps. THE BYTES ARE
# NOT HERE AND NEVER WILL BE -- only the ids and the sizes, which are
# observations about the format and are already published in the study doc.
BORROWED_IDS = (HEADER_CHUNK, WATER_CHUNK, LOCATIONS_CHUNK, COLLISION_CHUNK,
                WATER_DEPS_CHUNK)
BORROWED_SIZES = {HEADER_CHUNK: 8, WATER_CHUNK: 5, LOCATIONS_CHUNK: 13,
                  COLLISION_CHUNK: 9, WATER_DEPS_CHUNK: 197}
BORROWED_BYTES = sum(BORROWED_SIZES.values())               # 232

# The four base ids whose `s_chunkInfo` load pointer is NULL: the client fetches
# it and jumps without a null check (FINDINGS 3, FINDINGS 17.5). Never author one.
NULL_LOAD_BASE_IDS = (0x01, 0x05, 0x0B, 0x0D)
MAX_BASE_ID = 0x16
BLOATED_STAGE = 2

# ------------------------------------------------------------ Map Parameters

MAP_PARAMS_SIG = 0x5943EEEF
MAP_PARAMS_VERSION = 2
MAP_PARAMS_SIZE = 41
MAP_PARAMS_REJECTED_SIZE = 16      # the one size with its own gate, FINDINGS 17.4
_MP_HEAD = struct.Struct("<IB")    # sig then a VERSION BYTE -- so the rect
_MP_RECT = struct.Struct("<4f")    # floats begin at the UNALIGNED offset +5
_MP_FLAGS = struct.Struct("<I")
MAP_PARAMS_UUID_LEN = 16
ZERO_UUID = bytes(MAP_PARAMS_UUID_LEN)

ORIGIN_GENERATED = "generated"
ORIGIN_CARRIED = "carried"


class NoConstants(ValueError):
    """No archive, so the five FINDINGS 14 constants cannot be borrowed at run time.

    A named error rather than a bare ValueError because it is the one refusal
    this module exists to make: the alternative -- shipping 232 ArenaNet bytes
    inside the repo so a build works offline -- is permanently unavailable, and
    a caller that catches this should say so rather than fall back.
    """


# --------------------------------------------------------- borrowed material

def borrowed_constants(archive, donor_row=None, exclude_row=None, index=None):
    """The five FINDINGS 14 constants, read out of the owner's own archive right now.

    Returns `{chunk_id: bytes}` for exactly `BORROWED_IDS`, plus the donor row it
    read them from, as `(constants, donor_row)`.

    `donor_row` defaults to the SMALLEST map head that is not `exclude_row`.
    Reading them from a different map than the one being rebuilt is deliberate:
    FINDINGS 14's claim is that these five are constant corpus-wide, and a build that
    still lands byte-identical on its target is evidence for that claim. Reading
    them out of the target would make the identity unfalsifiable.

    Raises `NoConstants` if `archive` is None, and ValueError if the donor is
    missing any of the five -- never a partial dict, because a missing constant
    would otherwise surface as a mysteriously short map file.
    """
    if archive is None:
        raise NoConstants(
            "cannot build: the five mandatory chunks 0x20000000, 0x20000006, "
            "0x2000000A, 0x2000000E and 0x21000006 are byte-identical ArenaNet "
            "constants (FINDINGS 14, 232 bytes per map) and CLAUDE.md's "
            "provenance gate keeps them out of this repo permanently, so they "
            "are read from the owner's own Gw.dat at run time. Pass "
            "archive=Archive(...) -- there is no offline fallback and there "
            "will not be one.")
    if donor_row is None:
        idx = index if index is not None else MapIndex(archive)
        heads = [h for h in idx.heads if h.index != exclude_row]
        if not heads:
            raise ValueError(f"{archive.path} has no map head to borrow the "
                             f"FINDINGS 14 constants from")
        donor_row = min(heads, key=lambda e: e.size).index
    entry = next((e for e in archive.entries if e.index == donor_row), None)
    if entry is None:
        raise ValueError(f"donor row {donor_row} does not exist in {archive.path}")
    donor = MapFile.decode(archive.read(entry))
    out = {}
    for cid in BORROWED_IDS:
        c = donor.find(cid)
        if c is None:
            raise ValueError(
                f"donor row {donor_row} has no chunk 0x{cid:08X} "
                f"({chunk_label(cid)}); FINDINGS 14 says all 349 maps carry "
                f"it, so either the donor is not a map or that claim is wrong")
        out[cid] = c.payload()
    return out, donor_row


def check_borrowed(constants):
    """Sizes of the borrowed chunks against FINDINGS 14's published sizes.

    Not a checksum -- the bytes are not ours to compare against. A size that
    disagrees means the donor is not the kind of file FINDINGS 14 measured, and the
    build should stop rather than emit a map with a wrong-length constant in it.
    """
    bad = []
    for cid, want in BORROWED_SIZES.items():
        got = len(constants.get(cid, b""))
        if got != want:
            bad.append(f"0x{cid:08X} ({chunk_label(cid)}) is {got} B, "
                       f"FINDINGS 14 measured {want} B in 349/349 maps")
    return bad


# ------------------------------------------------------- Map Parameters codec

def encode_map_parameters(rect, flags=0, uuid=ZERO_UUID,
                          version=MAP_PARAMS_VERSION, signature=MAP_PARAMS_SIG):
    """The 41-byte Map Parameters payload. Every byte of it is read by the client.

    The version is a **byte**, not a word (FINDINGS 17.4), so the four rect floats begin
    at the unaligned offset +5. A writer that pads to align them emits a chunk
    the client rejects, and the mistake is invisible in a hex dump unless you
    know to look for it -- which is why `_MP_HEAD` is `<IB` and the rect is
    packed separately instead of one `<IB4fI16s` struct that any future edit
    might "tidy" into alignment.

    The rect is copied by the client with NO validation at all -- no clamp, no
    NaN test, no `x1 >= x0`, zero x87 instructions in the whole reader -- and is
    then handed to Terrain. Getting it wrong misplaces the world silently.
    """
    uuid = bytes(uuid)
    if len(uuid) != MAP_PARAMS_UUID_LEN:
        raise ValueError(f"the map's content id is {len(uuid)} bytes, not "
                         f"{MAP_PARAMS_UUID_LEN}")
    if not 0 <= version <= 0xFF:
        raise ValueError(f"version {version} is a byte field")
    rect = tuple(float(v) for v in rect)
    if len(rect) != 4:
        raise ValueError(f"rect {rect} is not (x0, y0, x1, y1)")
    out = bytearray(_MP_HEAD.pack(signature, version))
    out += _MP_RECT.pack(*rect)
    out += _MP_FLAGS.pack(flags & 0xFFFFFFFF)
    out += uuid
    if len(out) != MAP_PARAMS_SIZE:
        raise ValueError(f"map parameters came out {len(out)} bytes, not "
                         f"{MAP_PARAMS_SIZE}")
    return bytes(out)


def decode_map_parameters(payload):
    """`(rect, flags, uuid, version, signature)`. Reproduces the client's gates.

    Both hard gates are applied here (signature, version) for the reason
    `mapexport.map_rect` gives: getting either wrong means we are reading a
    different chunk, and four floats of noise still parse.
    """
    if len(payload) < MAP_PARAMS_SIZE:
        raise ValueError(f"map parameters chunk is {len(payload)} bytes, under "
                         f"the client's `size >= {MAP_PARAMS_SIZE}` gate")
    signature, version = _MP_HEAD.unpack_from(payload, 0)
    if signature != MAP_PARAMS_SIG:
        raise ValueError(f"map parameters signature 0x{signature:08X} != "
                         f"0x{MAP_PARAMS_SIG:08X}")
    if version != MAP_PARAMS_VERSION:
        raise ValueError(f"map parameters version {version} != "
                         f"{MAP_PARAMS_VERSION}")
    rect = _MP_RECT.unpack_from(payload, _MP_HEAD.size)
    flags, = _MP_FLAGS.unpack_from(payload, _MP_HEAD.size + _MP_RECT.size)
    base = _MP_HEAD.size + _MP_RECT.size + _MP_FLAGS.size
    return (rect, flags, bytes(payload[base:base + MAP_PARAMS_UUID_LEN]),
            version, signature)


def default_rect(dim_x, dim_y):
    """The rect the client's own map constructor produces for these dims.

    `x0 = -(cx>>1)*3072`, `x1 = (cx-(cx>>1))*3072` with `cx = dimX/32` (FINDINGS 17.4).
    It matches the file bit-exactly on 348 of 349 maps -- including row 46196's
    literal NEGATIVE ZERO, which falls out of `-(0.0)` here and is why the
    negation is written outside the multiply. Row 29590 ships a symmetric rect
    instead, so this is a convention to follow and NOT a rule to enforce: no
    caller is required to use it and `gates()` does not test for it.
    """
    out = []
    for dim in (dim_x, dim_y):
        c = dim // CHUNK_SIZE
        out.append(-(float(c >> 1) * CHUNK_PITCH))
        out.append(float(c - (c >> 1)) * CHUNK_PITCH)
    return (out[0], out[2], out[1], out[3])


def random_uuid():
    """A fresh RFC 4122 v4 content id, which is what all 349 shipped maps carry.

    NOT the default. The client never reads these 16 bytes -- 349/349 are
    version 4 with 126 bits at 0.486-0.512 ones-frequency and the loader's nine
    compares touch none of them (FINDINGS 17.4) -- so zero is known-safe, and a
    deterministic default is what lets a build be diffed against another build.
    """
    return uuidlib.uuid4().bytes


# ---------------------------------------------------------- terrain from numbers

def _broadcast(value, n, what):
    """A scalar becomes `n` copies of itself; a sequence is taken as it stands.

    This is the whole "from numbers" claim in one function: row 46196's terrain
    chunk is 7,165 bytes and every array in it is uniform, so the builder is fed
    scalars and the arrays never exist as inputs at all.
    """
    if isinstance(value, int):
        if not 0 <= value <= 0xFF:
            raise ValueError(f"{what}: {value} is not a byte value")
        return bytes([value]) * n
    out = bytes(value)
    if len(out) != n:
        raise ValueError(f"{what}: {len(out)} bytes, expected {n}")
    return out


def _broadcast_f(value, n, what):
    if isinstance(value, (int, float)):
        return [float(value)] * n
    out = [float(v) for v in value]
    if len(out) != n:
        raise ValueError(f"{what}: {len(out)} values, expected {n}")
    return out


def make_terrain(dim_x, dim_y, heights=0.0, tiles=0, table_a=b"\x00",
                 table_b=b"\x00", bits=0, shade=0, shadow=None,
                 chunk_distance=8 * CHUNK_PITCH, angle=0.0, tex_word=0,
                 tex_f12=0.5, tex_f16=0.5, order=SEQUENCE_SHORT, tag3b=None):
    """A `terrain.Terrain` from parameters, each of which may be a scalar.

    `heights`, `tiles`, `bits` and `shade` accept either one value (broadcast
    over the grid) or the whole array. `shadow=None` builds one all-clear
    `ShadowBlock` per 32x32 chunk, which `trnshadow` run-codes to 544 bytes --
    exactly the corpus minimum, and what row 46196 actually ships.

    Nothing here validates dims: `Terrain.encode()` runs `validate()` and the
    loader's own two caps (`% 32`, `dimX*dimY <= 2^24`) live there. One gate,
    one place.
    """
    cells = dim_x * dim_y
    blocks = (dim_x // CHUNK_SIZE) * (dim_y // CHUNK_SIZE)
    table_a = bytes(table_a)
    table_b = bytes(table_b)
    if len(table_a) != len(table_b):
        raise ValueError(f"tile tables disagree: tag 4 has {len(table_a)} "
                         f"entries, tag 5 has {len(table_b)}")
    if shadow is None:
        shadow = [ShadowBlock([0] * trnshadow.BLOCK_EDGE) for _ in range(blocks)]
    return Terrain(dim_x, dim_y,
                   _broadcast_f(heights, cells, "heights"),
                   _broadcast(tiles, cells, "tiles"),
                   table_a, table_b,
                   _broadcast(bits, cells // 4, "tag 3 bits"),
                   _broadcast(shade, cells, "shade"),
                   shadow,
                   chunk_distance=chunk_distance, angle=angle,
                   tex_word=tex_word, tex_f12=tex_f12, tex_f16=tex_f16,
                   tag3b=tag3b, order=order)


def _uniform(seq):
    """The single value a sequence holds, or None if it holds more than one."""
    it = iter(seq)
    first = next(it, None)
    if first is None:
        return None
    for v in it:
        if v != first:
            return None
    return first


def terrain_parameters(trn):
    """`make_terrain` keyword arguments that reproduce this terrain.

    Every array that is uniform comes back as its scalar, so the returned dict
    IS the answer to "how many numbers is this terrain chunk". An all-clear
    shadow set comes back as `shadow=None` and is regenerated by the run coder
    rather than carried.
    """
    params = {
        "dim_x": trn.dim_x, "dim_y": trn.dim_y,
        "table_a": trn.table_a, "table_b": trn.table_b,
        "chunk_distance": trn.chunk_distance, "angle": trn.angle,
        "tex_word": trn.tex_word, "tex_f12": trn.tex_f12,
        "tex_f16": trn.tex_f16, "order": trn.order, "tag3b": trn.tag3b,
    }
    for name, array in (("heights", trn.heights), ("tiles", trn.tiles),
                        ("bits", trn.bits), ("shade", trn.shade)):
        one = _uniform(array)
        params[name] = array if one is None else one
    if all(not any(b.rows) for b in trn.shadow):
        params["shadow"] = None
    else:
        params["shadow"] = trn.shadow
    return params


def parameter_note(params):
    """One line per terrain parameter saying whether it is a number or an array.

    This is what makes "generated from typed parameters" checkable by a reader:
    on row 46196 every line says `number`, so the 7,165-byte chunk demonstrably
    came from fourteen numbers and two four-byte tables.
    """
    out = []
    for k in sorted(params):
        v = params[k]
        if v is None:
            out.append((k, "regenerated", "none"))
        elif isinstance(v, (int, float)):
            out.append((k, "number", repr(v)))
        elif isinstance(v, (bytes, bytearray)):
            out.append((k, f"array, {len(v)} B", v.hex() if len(v) <= 8 else ""))
        elif isinstance(v, tuple):
            out.append((k, "tuple", repr(v)))
        else:
            out.append((k, f"array, {len(v)} entries", ""))
    return out


# --------------------------------------------------------------- the report

class ChunkOrigin:
    """Where one emitted chunk's bytes came from. The honest half of the rung."""

    __slots__ = ("chunk_id", "size", "origin", "how")

    def __init__(self, chunk_id, size, origin, how):
        self.chunk_id = chunk_id
        self.size = size
        self.origin = origin
        self.how = how

    @property
    def label(self):
        return chunk_label(self.chunk_id)

    @property
    def generated(self):
        return self.origin == ORIGIN_GENERATED

    def __repr__(self):
        return (f"<ChunkOrigin 0x{self.chunk_id:08X} {self.size} B "
                f"{self.origin}>")


class BuildReport:
    """Per-chunk provenance for one build, in bytes, with the carried ones named.

    `framing` -- the four magic bytes, the type byte and the `{u32 id, u32 size}`
    table -- is counted as GENERATED, because our code writes it and every size
    in it is re-derived from the payload it precedes (`mapfile.MapFile.encode`).
    It is reported on its own line so a reader can move it if they disagree.
    """

    __slots__ = ("chunks", "source_row", "donor_row", "terrain_params",
                 "terrain_verbatim", "notes", "verified", "substituted")

    def __init__(self, chunks, source_row=None, donor_row=None,
                 terrain_params=None, terrain_verbatim=0, notes=()):
        self.chunks = list(chunks)
        self.source_row = source_row
        self.donor_row = donor_row
        self.terrain_params = terrain_params
        self.terrain_verbatim = terrain_verbatim
        self.notes = list(notes)
        self.verified = ()          # borrowed ids a DIFFERENT map corroborated
        self.substituted = ()       # borrowed ids that were not constant

    @property
    def framing(self):
        return FFNA_HEADER_LEN + CHUNK_HEADER.size * len(self.chunks)

    @property
    def payload_bytes(self):
        return sum(c.size for c in self.chunks)

    @property
    def total(self):
        return self.framing + self.payload_bytes

    @property
    def generated(self):
        return self.framing + sum(c.size for c in self.chunks if c.generated)

    @property
    def carried(self):
        return sum(c.size for c in self.chunks if not c.generated)

    @property
    def borrowed(self):
        """Of the carried bytes, the FINDINGS 14 constants specifically."""
        return sum(c.size for c in self.chunks
                   if not c.generated and c.chunk_id in BORROWED_IDS)

    @property
    def strict_generated(self):
        """Generated, minus terrain arrays emitted verbatim. See the docstring."""
        return self.generated - self.terrain_verbatim

    def pct(self, n):
        return 100.0 * n / self.total if self.total else 0.0

    def carried_chunks(self):
        return [c for c in self.chunks if not c.generated]

    def generated_chunks(self):
        return [c for c in self.chunks if c.generated]

    def summary(self):
        lines = []
        who = (f"row {self.source_row}" if self.source_row is not None
               else "nothing but numbers")
        lines.append(f"built from {who}; FINDINGS 14 constants borrowed from row "
                     f"{self.donor_row}")
        lines.append(f"  {self.total:>8} B total over {len(self.chunks)} chunks")
        lines.append(f"  {self.generated:>8} B generated  "
                     f"{self.pct(self.generated):6.2f}%   "
                     f"(framing {self.framing} B)")
        lines.append(f"  {self.carried:>8} B carried    "
                     f"{self.pct(self.carried):6.2f}%   "
                     f"(of which {self.borrowed} B are the five FINDINGS 14 constants)")
        if self.terrain_verbatim:
            whose = ("archive bytes" if self.source_row is not None
                     else "computed here from scalars, NOT borrowed")
            lines.append(f"  {self.strict_generated:>8} B generated, strictly  "
                         f"{self.pct(self.strict_generated):6.2f}%   "
                         f"(terrain arrays emitted verbatim: "
                         f"{self.terrain_verbatim} B, {whose})")
        if self.verified or self.substituted:
            lines.append(f"  {len(self.verified)} borrowed chunk(s) corroborated "
                         f"by row {self.donor_row}, {len(self.substituted)} "
                         f"found NOT constant and taken from the source")
        lines.append("  carried chunks, named:")
        for c in self.carried_chunks():
            lines.append(f"    0x{c.chunk_id:08X} {c.size:>6} B  {c.label}"
                         f"  [{c.how}]")
        for n in self.notes:
            lines.append(f"  note: {n}")
        return "\n".join(lines)


# ------------------------------------------------------------------ the spec

class MapSpec:
    """Typed parameters for one whole Bloated map file.

    `order` is the emitted chunk order and it is the file's, never a canonical
    one this module invents (see the module docstring).
    """

    __slots__ = ("order", "terrain_params", "rect", "flags", "uuid", "path",
                 "dependencies", "carried")

    def __init__(self, order, terrain_params=None, rect=None, flags=0,
                 uuid=ZERO_UUID, path=None, dependencies=None, carried=None):
        self.order = tuple(order)
        self.terrain_params = dict(terrain_params or {})
        self.rect = tuple(rect) if rect is not None else None
        self.flags = int(flags)
        self.uuid = bytes(uuid)
        self.path = path
        self.dependencies = dict(dependencies or {})    # id -> (entries, ver, sig)
        self.carried = dict(carried or {})              # id -> bytes

    def __repr__(self):
        return (f"<MapSpec {len(self.order)} chunks, "
                f"{len(self.carried)} carried>")


def build(spec, archive=None, constants=None, donor_row=None, index=None,
          constant_rows=None):
    """`(MapFile, BuildReport)` from typed parameters plus the FINDINGS 14 constants.

    Emission order is `spec.order` exactly. Every id in it must be accounted
    for by one of the five routes below, and an id that is not is a ValueError
    rather than a silently dropped chunk -- a short map file is the failure mode
    that would look like a success everywhere except the byte count.

    `constant_rows` names, per borrowed id, which row that constant actually
    came from. It exists because one of the five is not a constant (see the
    module docstring) and the report has to be able to say so.
    """
    constant_rows = dict(constant_rows or {})
    if constants is None:
        constants, donor_row = borrowed_constants(
            archive, donor_row=donor_row, index=index)
    bad = check_borrowed(constants)
    if bad:
        raise ValueError("borrowed FINDINGS 14 constants are the wrong size:\n  "
                         + "\n  ".join(bad))

    chunks, origins, verbatim = [], [], 0
    for cid in spec.order:
        if cid in BORROWED_IDS:
            payload = constants[cid]
            src_row = constant_rows.get(cid, donor_row)
            how = f"FINDINGS 14 constant, archive row {src_row}"
            if src_row != donor_row:
                how += f" -- donor row {donor_row} DISAGREED, so not a constant"
            chunks.append(Chunk(cid, payload, FORM_OPAQUE))
            origins.append(ChunkOrigin(cid, len(payload), ORIGIN_CARRIED, how))
        elif cid == TERRAIN_CHUNK:
            trn = make_terrain(**spec.terrain_params)
            chunks.append(Chunk(cid, trn, FORM_TERRAIN))
            payload = trn.encode()
            verbatim += mapfile.terrain_carried_bytes(trn)
            origins.append(ChunkOrigin(cid, len(payload), ORIGIN_GENERATED,
                                       "terrain.Terrain.encode"))
        elif cid == MAP_PARAMS_CHUNK:
            rect = spec.rect
            if rect is None:
                rect = default_rect(spec.terrain_params["dim_x"],
                                    spec.terrain_params["dim_y"])
            payload = encode_map_parameters(rect, spec.flags, spec.uuid)
            chunks.append(Chunk(cid, payload, FORM_OPAQUE))
            origins.append(ChunkOrigin(cid, len(payload), ORIGIN_GENERATED,
                                       "mapbuild.encode_map_parameters"))
        elif cid == PATHING_CHUNK:
            if spec.path is None:
                raise ValueError("the chunk order names 0x20000008 but the spec "
                                 "carries no navmesh")
            payload = spec.path.encode()
            chunks.append(Chunk(cid, payload, FORM_OPAQUE))
            origins.append(ChunkOrigin(cid, len(payload), ORIGIN_GENERATED,
                                       "pathchunk.PathChunk.encode"))
        elif cid in spec.dependencies:
            entries, version, signature = spec.dependencies[cid]
            dep = mapchunks.Dependencies(signature, version, entries)
            chunks.append(Chunk(cid, dep, FORM_DEPENDENCIES))
            payload = chunks[-1].payload()
            origins.append(ChunkOrigin(
                cid, len(payload), ORIGIN_GENERATED,
                f"mapchunks framing, {len(entries)} borrowed file ids"))
        elif cid in spec.carried:
            payload = bytes(spec.carried[cid])
            chunks.append(Chunk(cid, payload, FORM_OPAQUE))
            origins.append(ChunkOrigin(cid, len(payload), ORIGIN_CARRIED,
                                       "opaque, no codec for this kind yet"))
        else:
            raise ValueError(
                f"chunk 0x{cid:08X} ({chunk_label(cid)}) is in the order but "
                f"nothing supplies it: it is not a FINDINGS 14 constant, not terrain, "
                f"not map parameters, not the path chunk, and the spec has no "
                f"dependency entries or carried bytes for it")

    mf = MapFile(MAP_FFNA_TYPE, chunks)
    rep = BuildReport(origins, donor_row=donor_row,
                      terrain_params=spec.terrain_params,
                      terrain_verbatim=verbatim)
    rep.verified = tuple(cid for cid in BORROWED_IDS
                         if cid in spec.order
                         and constant_rows.get(cid, donor_row) == donor_row)
    rep.substituted = tuple(cid for cid in BORROWED_IDS
                            if constant_rows.get(cid, donor_row) != donor_row)
    for cid in rep.substituted:
        rep.notes.append(
            f"0x{cid:08X} ({chunk_label(cid)}) is NOT a corpus constant: row "
            f"{donor_row}'s copy differs, so this build used row "
            f"{constant_rows[cid]}'s own bytes. FINDINGS 14 lists it as taking "
            f"two values across the 349 maps.")
    return mf, rep


# ------------------------------------------------------- rebuild a known map

def spec_from_map(mf):
    """Pull a `MapSpec` out of a decoded map: parameters in, bytes only where
    no codec exists yet.

    The terrain chunk is NOT handed over as an object -- it is reduced to
    `make_terrain` arguments by `terrain_parameters`, so the rebuilt chunk comes
    from numbers and tables rather than from the decoded record list. That
    distinction is the difference between this rung and `mapfile.py`'s.
    """
    order = list(mf.ids)
    terrain_params, rect, flags, uuid, path = {}, None, 0, ZERO_UUID, None
    deps, carried = {}, {}
    for c in mf.chunks:
        cid = c.chunk_id
        if cid in BORROWED_IDS:
            continue
        if cid == TERRAIN_CHUNK:
            terrain_params = terrain_parameters(c.value)
        elif cid == MAP_PARAMS_CHUNK:
            rect, flags, uuid, _v, _s = decode_map_parameters(c.payload())
        elif cid == PATHING_CHUNK:
            path = PathChunk.from_chunk(c.payload())
        elif c.form == FORM_DEPENDENCIES:
            deps[cid] = (c.value.entries, c.value.version, c.value.signature)
        else:
            carried[cid] = c.payload()
    return MapSpec(order, terrain_params=terrain_params, rect=rect, flags=flags,
                   uuid=uuid, path=path, dependencies=deps, carried=carried)


def build_like(row, archive, donor_row=None, terrain_overrides=None, index=None):
    """Rebuild the map at MFT `row` from its own typed parameters.

    `terrain_overrides` is merged into the extracted terrain parameters, which
    is how a caller changes one thing (a height, the tile table) and sees what
    moves. With no overrides the output should be byte-identical to the archive's
    own bytes -- that is the acceptance test for this rung, and it is only half
    of it: read the report.

    THE BORROWED CONSTANTS ARE VERIFIED, NOT TRUSTED. Each of the five is taken
    from a different map and then compared against this map's own copy; where
    they differ the source's bytes win and the report says so. One of the five
    genuinely differs (see the module docstring), and a builder that trusted the
    donor would emit a wrong Water chunk on most of the corpus while passing on
    the two maps this rung was first tested against.
    """
    entry = next((e for e in archive.entries if e.index == row), None)
    if entry is None:
        raise ValueError(f"MFT row {row} does not exist in {archive.path}")
    source = MapFile.decode(archive.read(entry))
    spec = spec_from_map(source)
    if terrain_overrides:
        spec.terrain_params.update(terrain_overrides)
    if donor_row is None:
        constants, donor_row = borrowed_constants(archive, exclude_row=row,
                                                  index=index)
    else:
        constants, donor_row = borrowed_constants(archive, donor_row=donor_row,
                                                  index=index)
    constant_rows = {}
    for cid in BORROWED_IDS:
        own = source.find(cid)
        if own is None:
            continue                    # not in this map, so never emitted
        payload = own.payload()
        if payload != constants[cid]:
            constants[cid] = payload
            constant_rows[cid] = row
    mf, rep = build(spec, constants=constants, donor_row=donor_row,
                    constant_rows=constant_rows)
    rep.source_row = row
    return mf, rep


# --------------------------------------------------------- a map from numbers

# A subsequence of the corpus order (FINDINGS 3), and the smallest set that
# carries every FINDINGS 14 constant plus everything a loader needs: header, world rect,
# terrain, navmesh. Dependencies are OMITTED rather than emitted empty -- FINDINGS 17.5:
# an absent chunk kind is default-constructed, so omission is the documented
# behaviour and an empty dependency list is a guess about one.
FLAT_ORDER = (HEADER_CHUNK, MAP_PARAMS_CHUNK, COLLISION_CHUNK, TERRAIN_CHUNK,
              WATER_CHUNK, WATER_DEPS_CHUNK, PATHING_CHUNK, LOCATIONS_CHUNK)


def build_flat(dim_x=CHUNK_SIZE, dim_y=CHUNK_SIZE, height=0.0, archive=None,
               constants=None, donor_row=None, tile=0, tiles=1, shade=0,
               uuid=ZERO_UUID, flags=0, rect=None, sequence=0, order=FLAT_ORDER,
               index=None):
    """A whole map from nothing but numbers, plus the borrowed FINDINGS 14 constants.

    This is the authoring direction proper: no source map, no archive row to
    imitate, and every byte outside the 232 borrowed ones computed from the
    arguments. The navmesh is `pathchunk.PathChunk.minimal` -- one plane, one
    rectangular trapezoid, no portals -- whose point-location DAG is labelled
    INFERRED at its own call site and has never been loaded by a client.

    `tiles` is the size of the tile table; `tile` is the index every cell uses.
    The default `tiles=1` is the smallest legal table.
    """
    terrainmod._gate_dims(dim_x, dim_y)      # the loader's own two caps, once
    if rect is None:
        rect = default_rect(dim_x, dim_y)
    params = dict(dim_x=dim_x, dim_y=dim_y, heights=float(height), tiles=tile,
                  table_a=bytes(range(tiles)), table_b=bytes(tiles), bits=0,
                  shade=shade, shadow=None, order=SEQUENCE_SHORT)
    spec = MapSpec(order, terrain_params=params, rect=rect, flags=flags,
                   uuid=uuid,
                   path=PathChunk.minimal(rect=rect, sequence=sequence))
    return build(spec, archive=archive, constants=constants,
                 donor_row=donor_row, index=index)


# ------------------------------------------------------- the loader's rules

def _subsequence(small, big):
    it = iter(big)
    return all(any(x == y for y in it) for x in small)


def gates(mf, reference_order=None):
    """Every open-time rule FINDINGS 17.4/17.5 states, as (name, ok, detail).

    The control that makes this worth running is that a SHIPPED RETAIL MAP must
    pass all of them. A gate a real map fails is our misreading of the client,
    not the map's defect, so `test_mapbuild.py` runs this against row 46196's
    own bytes before it runs it against anything we built.

    UNVERIFIED end to end: no map built here has been loaded by a client. These
    are the rules the disassembly says the loader applies, not observations of
    it applying them.
    """
    out = []

    def g(name, ok, detail=""):
        out.append((name, bool(ok), detail))

    g("ffna type is 3 (a map)", mf.ffna_type == MAP_FFNA_TYPE,
      f"type {mf.ffna_type}")

    ids = mf.ids
    g("the Header chunk is present", HEADER_CHUNK in ids,
      "the one chunk with a NULL +0x00 default")

    bad_ids, stages = [], set()
    for cid in ids:
        try:
            kind = decompose(cid)
        except ValueError:
            bad_ids.append(f"0x{cid:08X} does not decompose")
            continue
        stages.add(kind.stage)
        if kind.base_id in NULL_LOAD_BASE_IDS:
            bad_ids.append(f"0x{cid:08X} has a NULL load pointer")
        if kind.base_id > MAX_BASE_ID:
            bad_ids.append(f"0x{cid:08X} base id past the 23-slot table")
    g("no chunk id the client would jump through", not bad_ids,
      "; ".join(bad_ids) or f"{len(ids)} ids, all in s_chunkInfo")
    g("every chunk is stage 2 (Bloated)", stages == {BLOATED_STAGE},
      f"stages {sorted(stages)}")

    mp = mf.find(MAP_PARAMS_CHUNK)
    rect = None
    if mp is None:
        g("map parameters present", False, "no 0x2000000C chunk")
    else:
        payload = mp.payload()
        try:
            rect, _flags, _u, ver, sig = decode_map_parameters(payload)
            ok = True
        except ValueError as exc:
            ok, ver, sig = False, None, None
            g("map parameters decode", False, str(exc))
        if ok:
            g("map parameters signature and version byte",
              sig == MAP_PARAMS_SIG and ver == MAP_PARAMS_VERSION,
              f"0x{sig:08X} v{ver}")
        g("map parameters size passes both size gates",
          len(payload) >= MAP_PARAMS_SIZE
          and len(payload) != MAP_PARAMS_REJECTED_SIZE,
          f"{len(payload)} B (>= {MAP_PARAMS_SIZE}, != "
          f"{MAP_PARAMS_REJECTED_SIZE})")
        if TERRAIN_CHUNK in ids:
            g("map parameters precede terrain",
              ids.index(MAP_PARAMS_CHUNK) < ids.index(TERRAIN_CHUNK),
              "terrain copies the rect out of the map object")

    trn = mf.terrain()
    if trn is None:
        g("terrain present", False, "no 0x20000002 chunk")
    else:
        g("dims are multiples of 32",
          trn.dim_x % CHUNK_SIZE == 0 and trn.dim_y % CHUNK_SIZE == 0,
          f"{trn.dim_x}x{trn.dim_y}")
        g("area under the loader's cap", trn.cells <= MAX_CELLS,
          f"{trn.cells} <= {MAX_CELLS}")
        g("terrain tag order is one the client's step table accepts",
          trn.order in (SEQUENCE_SHORT, SEQUENCE_LONG), f"{trn.order}")
        g("tag 0 chunk distance is a chunk multiple, >= 9216",
          trn.chunk_distance % CHUNK_PITCH == 0.0
          and trn.chunk_distance >= 3 * CHUNK_PITCH,
          f"{trn.chunk_distance}")
        if rect is not None:
            ex, ey = rect[2] - rect[0], rect[3] - rect[1]
            g("rect extent is the grid at 96.0 units a cell",
              ex == trn.dim_x * CELL_PITCH and ey == trn.dim_y * CELL_PITCH,
              f"{ex}x{ey} against {trn.dim_x * CELL_PITCH}x"
              f"{trn.dim_y * CELL_PITCH}")
            g("rect extent is a whole number of 3072-unit chunks",
              ex % CHUNK_PITCH == 0.0 and ey % CHUNK_PITCH == 0.0,
              f"{ex}, {ey}")

    pth = mf.find(PATHING_CHUNK)
    if pth is None:
        g("navmesh present", False, "no 0x20000008 chunk")
    else:
        pc = PathChunk.from_chunk(pth.payload())
        g("navmesh version is the Bloated one", pc.version == pathchunk.VERSION,
          f"v{pc.version}")
        g("navmesh sequence is not 0xFFFFFFFF", pc.sequence != 0xFFFFFFFF,
          f"{pc.sequence} (0xFFFFFFFF asserts and stops the client)")
        if rect is not None:
            ex, ey = rect[2] - rect[0], rect[3] - rect[1]
            g("obstacle grid covers the rect at 1024 units a cell",
              pc.obstacles.width * pathchunk.OBSTACLE_CELL == ex
              and pc.obstacles.height * pathchunk.OBSTACLE_CELL == ey,
              f"{pc.obstacles.width}x{pc.obstacles.height} cells")

    if reference_order is not None:
        g("chunk order is a subsequence of a real map's order",
          _subsequence(ids, list(reference_order)),
          f"{len(ids)} ids against a {len(list(reference_order))}-id reference")
    return out


# ------------------------------------------------------------ writing output

def working_tree_roots():
    """Every checkout of this repository that a write could land in.

    `REPO_ROOT` is the tree THIS file sits in, and in a git worktree that is
    NOT the main checkout: the worktree's `.git` is a file reading
    `gitdir: <main>/.git/worktrees/<name>`, and the main checkout -- tracked
    files and all -- lives somewhere else entirely. A refusal that tested
    `REPO_ROOT` alone therefore allowed `--out` to write a built map straight
    into the other tree of the same repository, which is the provenance gate
    failing in exactly the environment this module was written in. Measured:
    from the worktree, `<main>/toolkit/out.dat` was ALLOWED.

    Returns absolute paths, most specific first. Never raises -- an unreadable
    or unusual `.git` yields the roots we could establish, and the caller still
    refuses `REPO_ROOT`.
    """
    roots = [os.path.abspath(REPO_ROOT)]
    dotgit = os.path.join(REPO_ROOT, ".git")
    if not os.path.isfile(dotgit):
        return roots                            # a normal checkout, or no git
    try:
        with open(dotgit, "r", encoding="utf-8", errors="replace") as fh:
            line = fh.read().strip()
    except OSError:
        return roots
    if not line.startswith("gitdir:"):
        return roots
    gitdir = line.split(":", 1)[1].strip()
    if not os.path.isabs(gitdir):
        gitdir = os.path.join(REPO_ROOT, gitdir)
    # <main>/.git/worktrees/<name>  ->  <main>
    node = os.path.abspath(gitdir)
    while os.path.basename(node) != ".git":
        parent = os.path.dirname(node)
        if parent == node:
            return roots
        node = parent
    main = os.path.dirname(node)
    if main and not _inside(main, roots[0]):
        roots.append(main)
    return roots


def resolve_out(path):
    """Where a built map may be written. The working tree is refused, always.

    A `build_like` payload is derived ArenaNet data and a `build_flat` payload
    still carries the 232 borrowed bytes, so both are covered by the same rule
    `mapexport.resolve_outdir` applies to height fields. The vault sits inside
    the repo root in the main checkout and is gitignored, so it is allowed by
    name -- a plain prefix test would refuse the obvious destination.

    EVERY checkout is refused, not just this one: see `working_tree_roots`.
    """
    path = os.path.abspath(path)
    vault = os.path.abspath(vaultpath.vault_root())
    if _inside(path, vault):
        return path
    for root in working_tree_roots():
        if _inside(path, root):
            raise ValueError(
                f"refusing to write a built map into the working tree: {path}\n"
                f"  It carries the 232 bytes of FINDINGS 14 constants borrowed "
                f"from Gw.dat, and CLAUDE.md's provenance gate keeps ArenaNet "
                f"bytes out of this repo permanently.\n"
                f"  That tree is {root}"
                + (" -- the MAIN checkout, which this worktree shares a "
                   "repository with.\n" if root != os.path.abspath(REPO_ROOT)
                   else "\n")
                + f"  Write under {vaultpath.vault_path('builds')} or to a "
                f"scratch directory outside every checkout.")
    return path


def _inside(path, root):
    """True if `path` is `root` or below it. Case-folded: this is Windows."""
    path = os.path.normcase(os.path.abspath(path))
    root = os.path.normcase(os.path.abspath(root))
    return path == root or path.startswith(root + os.sep)


# ------------------------------------------------------------------- the CLI

def _main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dat", default=DEFAULT_DAT)
    ap.add_argument("--row", type=int, default=46196,
                    help="rebuild this map row from its own parameters")
    ap.add_argument("--file-id", default=None,
                    help="the map's file id instead of its MFT row")
    ap.add_argument("--donor-row", type=int, default=None,
                    help="borrow the five FINDINGS 14 constants from this row instead "
                         "of the smallest other map")
    ap.add_argument("--flat", default=None, metavar="WxH",
                    help="build a flat map of these dims instead of a rebuild")
    ap.add_argument("--height", type=float, default=0.0)
    ap.add_argument("--out", default=None,
                    help="write the payload here (inside the repo is refused)")
    ap.add_argument("--verbose", action="store_true",
                    help="every chunk and every terrain parameter")
    args = ap.parse_args(argv)

    with Archive(args.dat) as ar:
        idx = MapIndex(ar)
        if args.flat:
            dim_x, _, dim_y = args.flat.lower().partition("x")
            mf, rep = build_flat(int(dim_x), int(dim_y), height=args.height,
                                 archive=ar, donor_row=args.donor_row, index=idx)
            reference = None
            source = None
        else:
            row = args.row
            if args.file_id:
                row = file_id_table(ar).get(int(args.file_id, 0))
                if row is None:
                    print(f"no file id {args.file_id} in {args.dat}")
                    return 1
            entry = next((e for e in ar.entries if e.index == row), None)
            if entry is None:
                print(f"row {row} does not exist in {args.dat}")
                return 1
            source = ar.read(entry)
            mf, rep = build_like(row, ar, donor_row=args.donor_row, index=idx)
            reference = MapFile.decode(source).ids

        out = mf.encode()
        print(rep.summary())
        if source is not None:
            ok = out == source
            print(f"\n  round-trip against the archive: "
                  f"{'BYTE-IDENTICAL' if ok else 'DIFFERS'} "
                  f"({len(out)} vs {len(source)} bytes)")
            if not ok:
                n = min(len(out), len(source))
                first = next((i for i in range(n) if out[i] != source[i]), n)
                print(f"  first difference at byte {first}")
        else:
            ok = True
            print(f"\n  built {len(out)} bytes from nothing but numbers "
                  f"plus {rep.borrowed} borrowed")

        print("\n  the client's own open-time rules:")
        for name, good, detail in gates(mf, reference_order=reference):
            print(f"    [{'ok ' if good else 'NO '}] {name}"
                  + (f"  --  {detail}" if detail else ""))
            ok = ok and good

        if args.verbose:
            print(f"\n  {'chunk':>10} {'size':>8}  origin      how")
            for c in rep.chunks:
                print(f"  0x{c.chunk_id:08X} {c.size:>8}  "
                      f"{c.origin:<10}  {c.how}   {c.label}")
            if rep.terrain_params:
                print("\n  terrain parameters:")
                for k, kind, detail in parameter_note(rep.terrain_params):
                    print(f"    {k:<16} {kind:<18} {detail}")

        if args.out:
            dest = resolve_out(args.out)
            os.makedirs(os.path.dirname(dest) or ".", exist_ok=True)
            with open(dest, "wb") as fh:
                fh.write(out)
            print(f"\n  wrote {len(out)} bytes to {dest}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(_main())
