"""Check the map builder: assemble row 46196 from parameters, byte for byte.

THE HEADLINE IS ONE EQUALITY -- `build_like(46196)` produces the archive's own
8,471 bytes -- AND IT IS THE WEAKER HALF OF THE RUN. A program that copies 8,471
bytes passes it, and FINDINGS 14 makes a copying builder the *expected* shape for
232 of those bytes. So the equality never appears here without the census beside
it: how many bytes were GENERATED by our encoders from typed values, how many
were CARRIED verbatim, and which chunks the carried ones are, asserted against a
floor rather than printed.

MEASURED, and these are the floors section 4 asserts:

    8,471 B total     18 chunks
    7,814 B generated  92.24%   framing 149, Terrain 7,165, Path 419,
                                Map Parameters 41, Dependencies 40
      657 B carried     7.76%   8 opaque kinds (425 B) + the five FINDINGS 14
                                constants (232 B)
    5,502 B generated strictly, 64.95% -- the 2,312 bytes of terrain arrays that
                                reach the encoder as opaque `bytes` subtracted

THE CONTROL THAT MAKES IT MEAN ANYTHING. Section 5 rebuilds the same row with
ONE terrain parameter changed and requires the output to differ from the
archive's bytes inside chunk 0x20000002 and to be byte-identical everywhere
else -- checked chunk by chunk with a walk written here out of `int.from_bytes`.
A copier fails that: it has nowhere to put the change. The mirror control changes
the Map Parameters content id and requires 0x2000000C alone to move, which is
what stops "only terrain ever changes" from being an accident of the plumbing.

THE PROVENANCE GATE IS TESTED, NOT ASSUMED. FINDINGS 14's five constants are
ArenaNet's bytes and may never enter this repo. Section 0 requires the builder to
REFUSE (`NoConstants`) rather than fall back when there is no archive; section 2
reads `mapbuild.py`'s own SYNTAX TREE and requires no bytes literal longer than
two bytes in it; and section 7 does the exact version -- it takes the five
payloads it just read out of the archive and looks for them in BOTH source files,
raw, as hex, as spaced hex and as `\\x` escapes. That last one is not
hypothetical: a draft of `mapbuild.py` quoted the five bytes of the Water chunk
in its own docstring, in the middle of explaining that Water is not a constant,
and the syntax-tree scan could not see it because it was prose. This test file
holds no fixture containing them either -- sections 0-3 run the whole builder on
PLACEHOLDER constants of our own zero bytes, which is why they need no vault.

FINDINGS 14 IS ALSO A CLAIM THAT CAN FAIL HERE. The builder borrows the five
constants from a DIFFERENT map than the one it rebuilds, so byte-identity on row
46196 is evidence that they really are constant corpus-wide; section 4 checks
that the donor was not the source, and section 7 re-measures the constancy
directly across a sample of maps.

GATES: A SHIPPED MAP MUST PASS THEM. `mapbuild.gates()` reproduces the loader's
open-time rules from FINDINGS 17.4/17.5. A gate that rejects a retail map is our
misreading of the client, so section 6 runs the whole set against row 46196's own
bytes before running it against anything built here, and then breaks four rules
on purpose and requires each to go red alone.

A MISSING VAULT IS A FAILURE, NOT A SKIP. Sections 0-3 still run and their
checks are still printed, but they score 46 against a floor of 98, because a run
with no archive has proved nothing about ArenaNet's format and nothing at all
about the byte-identity this rung is named for.

    python toolkit/mapdata/test_mapbuild.py
    python toolkit/mapdata/test_mapbuild.py --sample 12
"""

import argparse
import ast
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
import checks  # noqa: E402
import vaultpath  # noqa: E402
from archive import Archive  # noqa: E402
from mapchunks import MapIndex  # noqa: E402
import mapfile  # noqa: E402
from mapfile import MapFile  # noqa: E402
import mapbuild  # noqa: E402
from mapbuild import (BORROWED_IDS, BORROWED_SIZES, MAP_PARAMS_CHUNK,  # noqa: E402
                      MAP_PARAMS_SIZE, NoConstants, build, build_flat,
                      build_like, decode_map_parameters, default_rect,
                      encode_map_parameters, gates, make_terrain, resolve_out,
                      spec_from_map, terrain_parameters)
from pathchunk import PATHING_CHUNK  # noqa: E402
from terrain import TERRAIN_CHUNK, Terrain  # noqa: E402

TARGET_ROW = 46196                      # the smallest complete retail map

# MEASURED on vault/dat_study/Gw.dat, 2026-08-11. Floors, not guesses: every one
# of these came off a green run of this file and is asserted with `>=` where a
# better builder could legitimately improve it and with `==` where it could not.
EXPECT_TOTAL = 8471
EXPECT_CHUNKS = 18
EXPECT_GENERATED = 7814
EXPECT_CARRIED = 657
EXPECT_BORROWED = 232                   # == sum(BORROWED_SIZES.values())
EXPECT_STRICT = 5502
EXPECT_PCT = 92.0                       # the headline, floored a little under
EXPECT_CARRIED_KINDS = 13               # 8 opaque + the five constants
GATE_COUNT = 18                         # 17 from FINDINGS 17.4/17.5, +1 from
                                        # FINDINGS 30: every REACHABLE plane
                                        # above 0 names a prop that exists

LEDGER = checks.Ledger("map builder", floor=99)
check = checks.adopt(LEDGER)


# --------------------------------------------------------------------------
# An independent chunk walk. Imports nothing from mapfile or mapbuild: every
# per-chunk claim below is only evidence because it is read back out of the
# emitted bytes by different code.

def walk(blob):
    """[(chunk_id, payload)] out of an `ffna` file, or a ValueError."""
    if len(blob) < 5 or blob[:4] != b"ffna":
        raise ValueError(f"not an ffna file: {blob[:4]!r}")
    out, p = [], 5
    while p < len(blob):
        if p + 8 > len(blob):
            raise ValueError(f"chunk header runs off the end at {p}")
        cid = int.from_bytes(blob[p:p + 4], "little")
        size = int.from_bytes(blob[p + 4:p + 8], "little")
        body = p + 8
        if body + size > len(blob):
            raise ValueError(f"chunk 0x{cid:08X} declares {size} at {body}")
        out.append((cid, bytes(blob[body:body + size])))
        p = body + size
    return out


def chunk_map(blob):
    return dict(walk(blob))


def refuses(fn, *a, **kw):
    """True if the call raises ValueError -- a refusal, not a crash."""
    try:
        fn(*a, **kw)
    except ValueError:
        return True
    except Exception:
        return False
    return False


def holds(fn):
    """Evaluate a predicate over possibly-broken bytes. Never raises."""
    try:
        return bool(fn())
    except Exception:
        return False


def attempt(fn):
    """Like `holds`, but returns the VALUE (or None). Never raises.

    Written after `holds` was used where a value was wanted: `bool(dict)` is
    True, so three checks that should have read chunks out of a rebuilt file
    silently compared nothing and went red for the wrong reason.
    """
    try:
        return fn()
    except Exception:
        return None


def terrain_records(payload):
    """[(tag, body offset, size)] out of a terrain chunk, `int.from_bytes` only.

    Its own walker so the offsets this test reads terrain values at are not the
    ones `terrain.py` wrote them at. The header is EIGHT bytes here and TWELVE
    in the pathing chunk; using the wrong one desyncs the first record.
    """
    out, p = [], 8
    while p < len(payload):
        tag = payload[p]
        size = int.from_bytes(payload[p + 1:p + 5], "little")
        out.append((tag, p + 5, size))
        p = p + 5 + size
    return out


def guarded(fn, *a):
    """An exception inside a section becomes a named FAIL, not a traceback."""
    try:
        return fn(*a)
    except Exception as exc:
        check(False, f"section {fn.__name__} ran to completion",
              f"{type(exc).__name__}: {exc}")
        return None


def placeholder_constants():
    """OUR zero bytes at FINDINGS 14's measured sizes -- never ArenaNet's.

    This is what lets sections 1 and 3 run the whole assembly path on a bare
    machine. The resulting map is NOT loadable: a zeroed Header fails the
    client's own signature gate, and nothing here pretends otherwise. What it
    exercises is the builder's order, framing, census and refusals, all of which
    are ours.
    """
    return {cid: bytes(n) for cid, n in BORROWED_SIZES.items()}


# --------------------------------------------------------------------------

def section0():
    print("\n-- 0. the refusal: no archive, no build")
    check(refuses(mapbuild.borrowed_constants, None),
          "borrowed_constants(None) refuses instead of returning a partial dict")
    try:
        build_flat(32, 32)
        raised = None
    except NoConstants as exc:
        raised = exc
    except Exception as exc:                       # noqa: BLE001 -- reported
        raised = exc
    check(isinstance(raised, NoConstants),
          "build_flat with no archive raises NoConstants, a NAMED error",
          f"{type(raised).__name__}")
    msg = str(raised)
    check(all(s in msg for s in ("0x20000000", "0x21000006", "provenance")),
          "and the message names the chunks and says why they are not here",
          "a refusal a reader cannot act on is a crash with better manners")
    check(issubclass(NoConstants, ValueError),
          "NoConstants is a ValueError, so existing callers still catch it")

    spec = mapbuild.MapSpec((mapbuild.HEADER_CHUNK,))
    check(refuses(build, spec), "build() with no archive and no constants refuses")

    short = {cid: b"" for cid in BORROWED_IDS}
    check(refuses(build, spec, constants=short),
          "a donor whose constants are the wrong size stops the build",
          "a short constant would surface only as a mysteriously small map")


def section1():
    print("\n-- 1. Map Parameters, packed by hand and read back")
    rect = (-3072.0, -6144.0, 3072.0, 6144.0)
    uid = bytes(range(16))
    blob = encode_map_parameters(rect, flags=0x03000020, uuid=uid)
    check(len(blob) == MAP_PARAMS_SIZE == 41,
          "the payload is 41 bytes, the client's `size >= 41` gate", f"{len(blob)}")
    check(int.from_bytes(blob[0:4], "little") == 0x5943EEEF and blob[4] == 2,
          "signature 0x5943EEEF then the version as a SINGLE BYTE at +4")
    check(struct.unpack_from("<4f", blob, 5) == rect,
          "so the four rect floats start at the UNALIGNED offset +5",
          "a writer that pads to align them emits a chunk the client rejects")
    check(int.from_bytes(blob[0x15:0x19], "little") == 0x03000020
          and blob[0x19:0x29] == uid,
          "flags at +0x15 and the 16-byte content id at +0x19")
    got = decode_map_parameters(blob)
    check(got[0] == rect and got[1] == 0x03000020 and got[2] == uid,
          "and it decodes back to the values that went in")

    # THE NAMED CONTROL, and its outcome is not the one this check first
    # asserted. The mistake FINDINGS 17.4 warns about is a packer that writes
    # the version as a u32 and so aligns the rect to +8. Those bytes are NOT
    # refused -- by us or by the client: the low byte of a u32 2 is still 2, so
    # the signature gate and the version gate both pass and the loader copies
    # four floats of rubbish into the world rect with no validation whatever.
    # The failure is SILENT, which is exactly why `encode_map_parameters` packs
    # `<IB` and the rect separately instead of one tidy struct.
    aligned = (struct.pack("<II", 0x5943EEEF, 2) + struct.pack("<4f", *rect)
               + struct.pack("<I", 0) + uid)
    aligned_rect = decode_map_parameters(aligned)[0]
    check(len(aligned) == 44 and aligned_rect != rect,
          "the aligned-version-word packer passes both hard gates and yields a "
          "DIFFERENT rect -- it fails silently, it does not get refused",
          f"{aligned_rect} instead of {rect}; a writer that pads to align the "
          f"floats misplaces the world and gets no error for it")
    check(blob[5:9] != aligned[5:9],
          "and our encoder does not produce those bytes",
          "the rect starts at +5 here and at +8 there")
    check(refuses(decode_map_parameters, blob[:16]),
          "so is a 16-byte payload, the one size with a gate of its own")
    check(refuses(decode_map_parameters, b"\x00" * 41),
          "so is a payload with the wrong signature")
    bad_ver = bytearray(blob)
    bad_ver[4] = 3
    check(refuses(decode_map_parameters, bytes(bad_ver)),
          "so is version 3")
    check(refuses(encode_map_parameters, rect, uuid=b"\x00" * 15),
          "and a 15-byte content id will not encode")

    r = default_rect(32, 32)
    packed = struct.pack("<4f", *r)
    check(r == (-0.0, -0.0, 3072.0, 3072.0) and packed[3] == 0x80,
          "default_rect(32,32) reproduces row 46196's LITERAL NEGATIVE ZERO",
          "the client's constructor formula; the sign bit is really set")
    check(default_rect(128, 64) == (-6144.0, -3072.0, 6144.0, 3072.0),
          "and centres a 128x64 grid the way that formula does")


def section2():
    print("\n-- 2. the provenance gate, on this module's own source")
    src = open(mapbuild.__file__, "rb").read()
    text = src.decode("utf-8", "replace")
    # A payload of ArenaNet bytes could only be here as a literal. Look for the
    # shapes: a long bytes literal, a hex blob, base64, or an embedded file.
    long_hex = [w for w in text.replace('"', " ").replace("'", " ").split()
                if len(w) >= 24 and all(c in "0123456789abcdefABCDEF" for c in w)]
    check(not long_hex, "no hex literal long enough to be a borrowed constant",
          f"{long_hex[:2]}")
    check("fromhex" not in text and "b64decode" not in text,
          "no bytes.fromhex and no base64 decode anywhere in the module")
    # Read the module's own syntax tree rather than its text: a payload could
    # only be here as a bytes constant, and the smallest of the five is 5 bytes.
    big = [c.value for c in ast.walk(ast.parse(text))
           if isinstance(c, ast.Constant) and isinstance(c.value, bytes)
           and len(c.value) > 2]
    check(not big, "no bytes literal in the module is longer than two bytes",
          f"the smallest FINDINGS 14 constant is 5 B; found {big[:2]}")
    check(mapbuild.BORROWED_BYTES == sum(BORROWED_SIZES.values()) == 232,
          "the module states the 232 borrowed bytes as a SIZE and nothing more")

    root = mapbuild.REPO_ROOT
    check(os.path.isfile(os.path.join(root, "CLAUDE.md")),
          "REPO_ROOT resolves to the actual repo root", root)
    check(refuses(resolve_out, os.path.join(root, "toolkit", "built.ffna")),
          "writing a built map into the working tree is REFUSED")
    check(refuses(resolve_out, os.path.join(root, "x.ffna")),
          "including at the repo root itself")
    # A git WORKTREE's repo root is not the main checkout's, and a built map
    # written into the other tree is under version control just the same. This
    # went red before `working_tree_roots` existed: from the worktree this rung
    # was developed in, <main>/toolkit/out.dat was ALLOWED.
    #
    # The other tree is resolved HERE, out of `.git` directly, and NOT by asking
    # `mapbuild.working_tree_roots()` what it thinks the trees are. The first
    # version did ask, and a sabotage that crippled that function to return one
    # root passed this check 98 to 0 -- the defect and the oracle were the same
    # code. In a plain checkout `other` is the repo root, so the check still
    # asserts something and the count does not move between the two layouts.
    other = root
    dotgit = os.path.join(root, ".git")
    if os.path.isfile(dotgit):
        line = open(dotgit, encoding="utf-8", errors="replace").read().strip()
        gitdir = os.path.abspath(os.path.join(root, line.split(":", 1)[1].strip()))
        while os.path.basename(gitdir) != ".git" and os.path.dirname(gitdir) != gitdir:
            gitdir = os.path.dirname(gitdir)
        other = os.path.dirname(gitdir)
    check(refuses(resolve_out, os.path.join(other, "toolkit", "built.ffna")),
          "and the OTHER checkout of this repo is refused too",
          f"{other} -- read out of .git here, not from the module under test; "
          f"{'a worktree, so this is the main checkout' if other != root else 'a plain checkout, so it is this tree'}")
    inside_vault = vaultpath.vault_path("builds", "x.ffna")
    check(resolve_out(inside_vault) == os.path.abspath(inside_vault),
          "and the gitignored vault is allowed by name, not by prefix",
          "the vault sits INSIDE the repo root in the main checkout")


def section3():
    print("\n-- 3. a whole map from nothing but numbers")
    consts = placeholder_constants()
    mf, rep = build_flat(64, 32, height=-1000.0, tiles=3, tile=1,
                         constants=consts, donor_row="placeholder")
    blob = mf.encode()
    parts = walk(blob)
    ids = [cid for cid, _p in parts]
    check(len(blob) == rep.total and len(parts) == len(rep.chunks) == 8,
          "the report's byte total and chunk count are the file's",
          f"{len(blob)} B, {len(parts)} chunks")
    check(rep.framing == 5 + 8 * len(parts) == 69,
          "framing is the magic, the type byte and the chunk table", "69 B")
    check(sum(len(p) for _c, p in parts) + rep.framing == len(blob),
          "and every byte of the file is either framing or a chunk payload")
    check(rep.carried == rep.borrowed == 232,
          "everything carried is a FINDINGS 14 constant; nothing else is copied",
          f"carried {rep.carried} B, borrowed {rep.borrowed} B")
    check(rep.generated == len(blob) - 232,
          "so all the other bytes were generated here", f"{rep.generated} B")

    check(refuses(MapFile.decode, blob),
          "a STRICT decode refuses this file, and should: the placeholder "
          "0x21000006 is our zero bytes and not a Dependencies chunk",
          "which is also the check that these placeholders are not ArenaNet's")
    rt = MapFile.decode(blob, strict=False)
    check(rt.ffna_type == 3 and rt.ids == ids,
          "it decodes back through mapfile.MapFile as an ffna type-3 map")
    check([c.chunk_id for c in rt.failures()] == [mapbuild.WATER_DEPS_CHUNK],
          "and the ONE chunk it could not read is the placeholder, named")
    trn = rt.terrain()
    check(isinstance(trn, Terrain) and (trn.dim_x, trn.dim_y) == (64, 32),
          "and its terrain chunk decodes to the dims that were asked for",
          f"{trn.dim_x}x{trn.dim_y}")
    check(len(trn.heights) == 64 * 32 and set(trn.heights) == {-1000.0},
          "with the height field the caller passed as ONE NUMBER, broadcast",
          f"{len(trn.heights)} samples")
    check(len(trn.table_a) == 3 and len(trn.shadow) == 2 * 1,
          "the tile table it asked for and one shadow block per 32x32 chunk")
    check(Terrain.decode(chunk_map(blob)[TERRAIN_CHUNK]).encode()
          == chunk_map(blob)[TERRAIN_CHUNK],
          "and that chunk survives a decode/encode round trip of its own")

    rect = decode_map_parameters(chunk_map(blob)[MAP_PARAMS_CHUNK])[0]
    check(rect[2] - rect[0] == 64 * 96.0 and rect[3] - rect[1] == 32 * 96.0,
          "the rect is the grid at 96.0 units a cell, on both axes", f"{rect}")
    # The centring formula re-derived here rather than compared to itself. Note
    # it is NOT symmetric on an odd chunk count: 32 cells is one chunk, so the
    # y range is [-0.0, 3072] and not [-1536, 1536]. That asymmetry is the
    # client's own and row 46196 ships it.
    want = []
    for dim in (64, 32):
        c = dim // 32
        want.append((-(float(c >> 1) * 3072.0), float(c - (c >> 1)) * 3072.0))
    check(rect == (want[0][0], want[1][0], want[0][1], want[1][1]),
          "and it is the client's own constructor formula, re-derived here",
          f"{rect}")

    bad = [n for n, ok, _d in gates(mf) if not ok]
    check(not bad, "every open-time rule FINDINGS 17.4/17.5 states is satisfied",
          "; ".join(bad) or f"{len(gates(mf))} gates")

    check(refuses(build_flat, 30, 32, constants=consts),
          "dims that are not multiples of 32 are refused before anything is built")
    check(refuses(make_terrain, 32, 32, heights=[0.0] * 5),
          "a height field of the wrong length is refused, not padded")
    check(refuses(make_terrain, 32, 32, table_a=b"\x00\x01", table_b=b"\x00"),
          "and tile tables of different lengths are refused")


# --------------------------------------------------------------------------
# Everything below needs the archive.

def section4(ar, mi):
    print(f"\n-- 4. row {TARGET_ROW} rebuilt from its parameters, and the census")
    entry = next(e for e in ar.entries if e.index == TARGET_ROW)
    source = ar.read(entry)
    mf, rep = build_like(TARGET_ROW, ar, index=mi)
    out = mf.encode()

    check(out == source, "BYTE-IDENTICAL to the archive's own map file",
          f"{len(out)} vs {len(source)} bytes")
    check(len(source) == EXPECT_TOTAL and len(rep.chunks) == EXPECT_CHUNKS,
          f"the target is still {EXPECT_TOTAL} B over {EXPECT_CHUNKS} chunks",
          f"{len(source)} B, {len(rep.chunks)} chunks")
    check(rep.donor_row != TARGET_ROW,
          "the FINDINGS 14 constants came from a DIFFERENT map",
          f"donor row {rep.donor_row} -- which is what makes the equality above "
          f"evidence for FINDINGS 14 rather than a tautology")

    # -- the census, with floors --------------------------------------------
    print(f"   {rep.generated} B generated ({rep.pct(rep.generated):.2f}%), "
          f"{rep.carried} B carried ({rep.pct(rep.carried):.2f}%)")
    check(rep.total == len(source) == rep.framing + rep.payload_bytes,
          "the census accounts for every byte of the file",
          f"{rep.framing} framing + {rep.payload_bytes} payload")
    check(rep.generated + rep.carried == rep.total,
          "and each byte is counted exactly once, generated or carried")
    check(rep.generated >= EXPECT_GENERATED,
          f"generated bytes clear the floor of {EXPECT_GENERATED}",
          f"{rep.generated} B")
    check(rep.pct(rep.generated) >= EXPECT_PCT,
          f"which is at least {EXPECT_PCT}% of the file",
          f"{rep.pct(rep.generated):.2f}%")
    check(rep.carried <= EXPECT_CARRIED,
          f"carried bytes stay at or under {EXPECT_CARRIED}", f"{rep.carried} B")
    check(rep.borrowed == EXPECT_BORROWED == sum(BORROWED_SIZES.values()),
          "232 of those carried bytes are the five FINDINGS 14 constants",
          f"{rep.borrowed} B")
    check(rep.strict_generated >= EXPECT_STRICT
          and rep.terrain_verbatim == rep.generated - rep.strict_generated,
          f"the STRICTER figure clears {EXPECT_STRICT} B too",
          f"{rep.strict_generated} B ({rep.pct(rep.strict_generated):.2f}%) once "
          f"{rep.terrain_verbatim} B of terrain arrays are subtracted")

    carried = rep.carried_chunks()
    check(len(carried) == EXPECT_CARRIED_KINDS
          and sum(c.size for c in carried) == rep.carried,
          f"{EXPECT_CARRIED_KINDS} chunks are carried and each is NAMED",
          ", ".join(f"0x{c.chunk_id:08X}" for c in carried))
    check(all(c.how for c in carried) and all(c.how for c in rep.chunks),
          "every chunk in the report says how its bytes were produced")
    borrowed_named = {c.chunk_id for c in carried if c.chunk_id in BORROWED_IDS}
    check(borrowed_named == set(BORROWED_IDS),
          "all five constants are reported as carried, none as generated")
    gen_ids = {c.chunk_id for c in rep.generated_chunks()}
    check(gen_ids == {TERRAIN_CHUNK, MAP_PARAMS_CHUNK, PATHING_CHUNK,
                      0x21000002, 0x21000009},
          "and the generated set is terrain, map parameters, path and the two "
          "Dependencies chunks", f"{sorted(hex(i) for i in gen_ids)}")

    sizes = {c.chunk_id: c.size for c in rep.chunks}
    check(sizes.get(TERRAIN_CHUNK) == 7165 and sizes.get(PATHING_CHUNK) == 419
          and sizes.get(MAP_PARAMS_CHUNK) == 41,
          "the three big generated chunks are the measured sizes",
          "terrain 7,165, path 419, map parameters 41")

    # -- what the terrain was actually built from ---------------------------
    params = rep.terrain_params
    arrays = [k for k, v in params.items()
              if isinstance(v, (bytes, bytearray, list)) and k != "order"]
    check(set(arrays) <= {"table_a", "table_b"},
          "row 46196's 7,165-byte terrain chunk came from NUMBERS",
          f"the only array inputs are the two 4-byte tile tables: {arrays}")
    check(params.get("shadow") is None,
          "its shadow block is regenerated by the run coder, not carried",
          "all-clear, and trnshadow emits the corpus-minimum 544 bytes")
    check(isinstance(params.get("heights"), float)
          and isinstance(params.get("tiles"), int),
          "the height field is one float and the tile field one byte value",
          f"heights={params.get('heights')}, tiles={params.get('tiles')}")
    return source, mf, rep


def section5(ar, mi, source):
    print("\n-- 5. the controls: a copier cannot pass these")
    base = chunk_map(source)

    mf2, _rep2 = build_like(TARGET_ROW, ar,
                            terrain_overrides={"heights": 123.5}, index=mi)
    out2 = mf2.encode()
    check(holds(lambda: len(out2) == len(source)),
          "changing every height leaves the file the same LENGTH",
          "floats are floats -- so length equality proves nothing on its own")
    got2 = chunk_map(out2)
    moved = sorted(cid for cid in base if base[cid] != got2.get(cid))
    check(moved == [TERRAIN_CHUNK],
          "and it changes chunk 0x20000002 and NOTHING else",
          f"moved: {[hex(c) for c in moved]}")
    check(set(got2) == set(base) and len(got2) == EXPECT_CHUNKS,
          "the other 17 chunks are byte-identical to the archive's")
    recs = attempt(lambda: dict((t, (o, n))
                                for t, o, n in terrain_records(got2[TERRAIN_CHUNK])))
    off, size = (recs or {}).get(1, (None, 0))
    heights = attempt(lambda: struct.unpack_from(f"<{size // 4}f",
                                                 got2[TERRAIN_CHUNK], off))
    check(heights is not None and set(heights) == {123.5} and len(heights) == 1024,
          "the new height really is in the emitted terrain payload",
          f"all {len(heights or ())} of tag 1's floats, found by a walker "
          f"written in this file")

    consts, donor = mapbuild.borrowed_constants(ar, exclude_row=TARGET_ROW,
                                                index=mi)
    # THE BASELINE IS A CONTROL BUILD, NOT THE ARCHIVE'S BYTES, and the reason
    # is the whole point of these checks. `consts` comes from a DONOR map, and
    # one of the five (Water) genuinely takes two values corpus-wide, so
    # whether the donor's Water agrees with this target's is a property of
    # which row happens to be the smallest map head in whichever Gw.dat is
    # mounted. It changed when dat_study was regenerated at build 38833 -- the
    # smallest head went 71496 -> 177749 and the donor landed on the OTHER of
    # Water's two corpus-wide values -- and that reddened these two checks
    # without a line of builder code moving. (The two values are deliberately
    # not written here: section 9 refuses any borrowed payload appearing in
    # this file, and it caught an earlier draft of this very comment.)
    # Diffing two builds that
    # share those constants isolates the one input that changed, which is the
    # only thing these checks are for; the byte-identity against ArenaNet's own
    # bytes is section 4's job and check 1 above, and the signature check right
    # below keeps the archive tie here too.
    ctl, _repc = build(spec_from_map(MapFile.decode(source)),
                       constants=consts, donor_row=donor)
    ctl_map = chunk_map(ctl.encode())
    ctl_vs_archive = sorted(cid for cid in base if base[cid] != ctl_map.get(cid))
    check(ctl_vs_archive in ([], [mapbuild.WATER_CHUNK]),
          "the unchanged control build differs from the archive's own bytes in "
          "NOTHING but the donor's Water chunk, if that",
          f"differs: {[hex(c) for c in ctl_vs_archive]}; donor row {donor}")

    uid = bytes(range(16))
    spec = spec_from_map(MapFile.decode(source))
    spec.uuid = uid
    mf3, _rep3 = build(spec, constants=consts, donor_row=donor)
    got3 = chunk_map(mf3.encode())
    moved3 = sorted(cid for cid in ctl_map if ctl_map[cid] != got3.get(cid))
    check(moved3 == [MAP_PARAMS_CHUNK],
          "a changed content id moves chunk 0x2000000C and only that one",
          f"moved: {[hex(c) for c in moved3]} -- so 'only terrain ever moves' "
          f"is not an accident of the plumbing")
    check(got3[MAP_PARAMS_CHUNK][0x19:0x29] == uid,
          "and the new id is at +0x19 where the client's reader looks")

    # A size that MOVES: the chunk table entry has to follow it.
    spec.terrain_params = dict(spec.terrain_params)
    spec.terrain_params["table_a"] = b"\x00\x01\x02\x03\x04"
    spec.terrain_params["table_b"] = b"\x00\x01\x02\x03\x04"
    spec.uuid = decode_map_parameters(base[MAP_PARAMS_CHUNK])[2]
    mf4, rep4 = build(spec, constants=consts, donor_row=donor)
    out4 = mf4.encode()
    got4 = attempt(lambda: chunk_map(out4))
    check(got4 is not None, "a longer tile table still produces a walkable file")
    check(holds(lambda: len(got4[TERRAIN_CHUNK])
                == len(base[TERRAIN_CHUNK]) + 2),
          "the terrain payload grows by the two extra table entries",
          "one byte in tag 4 and one in tag 5")
    check(holds(lambda: len(out4) == len(source) + 2
                and rep4.total == len(out4)),
          "the file and the report grow with it -- the chunk table's size "
          "field is DERIVED, not replayed", f"{len(out4)} vs {len(source)}")
    check(holds(lambda: sorted(c for c in ctl_map if ctl_map[c] != got4.get(c))
                == [TERRAIN_CHUNK]),
          "and still nothing outside 0x20000002 moved")


def section6(ar, mi, source, mf):
    print("\n-- 6. the loader's own rules, on a SHIPPED map first")
    retail = MapFile.decode(source)
    result = gates(retail, reference_order=retail.ids)
    bad = [n for n, ok, _d in result if not ok]
    check(not bad, f"all {len(result)} gates accept ArenaNet's own row "
          f"{TARGET_ROW}", "; ".join(bad) or "a gate a real map fails is OUR bug")
    # PINNED, NOT BOUNDED. This read `>= 17` while the set was already 18, so the
    # one gate the portal work added -- "every REACHABLE plane above 0 names a prop
    # that exists", the rule that came out of FINDINGS 30 after a bad plane_map
    # crashed a client twice -- could be deleted with this check still green. A
    # lower bound cannot notice a rule going missing, which is the only thing this
    # check is for. Raise the number deliberately when a gate is added.
    check(len(result) == GATE_COUNT,
          "and the gate set is the whole one, not a subset",
          f"{len(result)} rules against {GATE_COUNT} expected -- a gate that "
          f"vanishes has to redden something, and this is the something")
    built = gates(mf, reference_order=retail.ids)
    check([n for n, ok, _d in built if not ok] == [],
          "and it accepts the rebuild too, in the file's own chunk order")

    # Four rules broken on purpose. Each must go red, and alone.
    def names_red(m, reference=None):
        return sorted(n for n, ok, _d in gates(m, reference_order=reference)
                      if not ok)

    sick = MapFile.decode(source)
    sick.chunks = [c for c in sick.chunks if c.chunk_id != MAP_PARAMS_CHUNK]
    red = attempt(lambda: names_red(sick))
    check(bool(red) and any("map parameters" in n for n in red),
          "a map with no Map Parameters chunk is rejected", f"{red}")

    sick2 = MapFile.decode(source)
    mp = sick2.find(MAP_PARAMS_CHUNK)
    mp.value = mp.value[:16]
    red2 = attempt(lambda: names_red(sick2))
    check(bool(red2) and any("size gates" in n for n in red2),
          "so is the 16-byte Map Parameters payload the client rejects by size",
          f"{red2}")

    sick3 = MapFile.decode(source)
    i = sick3.ids.index(MAP_PARAMS_CHUNK)
    j = sick3.ids.index(TERRAIN_CHUNK)
    sick3.chunks[i], sick3.chunks[j] = sick3.chunks[j], sick3.chunks[i]
    red3 = attempt(lambda: names_red(sick3))
    check(red3 == ["map parameters precede terrain"],
          "terrain before Map Parameters is rejected, and ONLY that rule fires",
          f"{red3}")

    sick4 = MapFile.decode(source)
    sick4.chunks[2].chunk_id = 0x2000000D          # an Editor slot, NULL load
    red4 = attempt(lambda: names_red(sick4))
    check(red4 == ["no chunk id the client would jump through"],
          "a chunk id whose load pointer is NULL is rejected, alone", f"{red4}")

    sick5 = MapFile.decode(source)
    order = [c for c in sick5.ids if c != PATHING_CHUNK]
    red5 = attempt(lambda: names_red(sick5, reference=order))
    check(bool(red5) and any("subsequence" in n for n in red5),
          "and a chunk order no retail map exhibits is rejected", f"{red5}")


def section7(ar, mi, picks):
    print("\n-- 7. FINDINGS 14 re-measured: are the five really constant?")
    consts, donor = mapbuild.borrowed_constants(ar, exclude_row=TARGET_ROW,
                                                index=mi)
    distinct = {cid: set() for cid in BORROWED_IDS}
    seen = 0
    for row in picks:
        mfx = MapFile.decode(ar.read(next(e for e in ar.entries
                                          if e.index == row)))
        seen += 1
        for cid in BORROWED_IDS:
            c = mfx.find(cid)
            check_present = c is not None
            if check_present:
                distinct[cid].add(c.payload())
    check(seen >= 4, "the sample is big enough to refute anything", f"{seen} maps")
    check(all(distinct[cid] for cid in BORROWED_IDS),
          f"all five chunks are present in all {seen} sampled maps")
    varying = sorted(cid for cid in BORROWED_IDS if len(distinct[cid]) > 1)
    check(varying == [mapbuild.WATER_CHUNK],
          "FOUR of the five are byte-identical across the sample -- and one is "
          "NOT: 0x20000006 (Water)",
          f"varying: {[hex(c) for c in varying]}; FINDINGS 14 says two values, "
          f"and a builder that trusted 'constant' would emit the wrong one")
    check(len(distinct[mapbuild.WATER_CHUNK]) == 2,
          "and Water takes exactly the two values FINDINGS 14 records",
          f"{len(distinct[mapbuild.WATER_CHUNK])} distinct over {seen} maps")
    check(all(len(consts[cid]) == BORROWED_SIZES[cid] for cid in BORROWED_IDS),
          "and each is the size FINDINGS 14 published",
          ", ".join(f"0x{c:08X}={BORROWED_SIZES[c]}" for c in BORROWED_IDS))

    # THE EXACT PROVENANCE CHECK, which section 2 can only approximate without
    # an archive: take the five payloads we just read and look for them in the
    # source of both files, raw and in the three hex spellings a docstring or a
    # literal would use. This is not hypothetical -- an earlier draft of
    # mapbuild.py quoted the five bytes of the Water chunk in its own docstring
    # while explaining that Water is not a constant, and section 2's
    # bytes-literal scan did not see it because it was prose.
    leaks = []
    for path in (mapbuild.__file__, __file__):
        blob = open(path, "rb").read()
        text = blob.decode("utf-8", "replace")
        for cid, payload in consts.items():
            spellings = [payload.hex(), payload.hex().upper(),
                         payload.hex(" "), payload.hex(" ").upper(),
                         "".join(f"\\x{b:02x}" for b in payload)]
            if payload in blob or any(s in text for s in spellings):
                leaks.append(f"0x{cid:08X} in {os.path.basename(path)}")
    check(not leaks,
          "NONE of the five borrowed payloads appears in either source file",
          "; ".join(leaks) or "raw, hex, spaced hex and \\x escapes all checked "
          "against the bytes just read out of the archive")

    # The builder's own extraction, checked against a different module's decode.
    src = ar.read(next(e for e in ar.entries if e.index == TARGET_ROW))
    trn = MapFile.decode(src).terrain()
    rebuilt = make_terrain(**terrain_parameters(trn))
    check(rebuilt.encode() == trn.encode(),
          "terrain_parameters -> make_terrain is a round trip on a retail chunk",
          "the parameter reduction loses nothing")
    census = mapfile.byte_census(MapFile.decode(src))
    check(census["total"] == EXPECT_TOTAL,
          "and mapfile's own census agrees on the file's byte total",
          f"{census['total']} B")


def section8(ar, mi, picks):
    print("\n-- 8. build_flat with the REAL constants, and a second target")
    mf, rep = build_flat(32, 32, height=-13.0, archive=ar, index=mi)
    blob = mf.encode()
    check(len(blob) == rep.total and len(walk(blob)) == 8,
          "a 32x32 map from numbers plus 232 borrowed bytes",
          f"{len(blob)} B over 8 chunks")
    check(rep.carried == 232 and rep.generated == len(blob) - 232,
          "and only the five constants are carried", f"{rep.carried} B")
    retail_order = MapFile.decode(
        ar.read(next(e for e in ar.entries if e.index == TARGET_ROW))).ids
    bad = [n for n, ok, _d in gates(mf, reference_order=retail_order) if not ok]
    check(not bad, "it satisfies every gate, in an order a retail map exhibits",
          "; ".join(bad) or "including the subsequence rule")

    # A second retail map, chosen because its Water chunk DISAGREES with the
    # donor's -- the case a builder that trusted "constant" gets wrong.
    consts, donor = mapbuild.borrowed_constants(ar, exclude_row=TARGET_ROW,
                                                index=mi)
    other, other_src = None, None
    for e in sorted(mi.heads, key=lambda x: x.size)[:12]:
        if e.index == TARGET_ROW:
            continue
        blob = ar.read(e)
        w = chunk_map(blob).get(mapbuild.WATER_CHUNK)
        if w is not None and w != consts[mapbuild.WATER_CHUNK]:
            other, other_src = e.index, blob
            break
    if other is None:
        LEDGER.skip("the substitution path",
                    "no small map in this archive disagrees with the donor's "
                    "Water chunk, so the not-a-constant case was not exercised")
        return
    # donor_row= PINNED to the donor `other` was SELECTED against. Without it
    # build_like re-derives its own donor (exclude_row=other), and the two can
    # land on opposite sides of Water's two values -- which is exactly what
    # 38833 did (selection donor 177749, build_like's donor 46196), leaving the
    # substitution path unexercised while four checks about it went red.
    mf2, rep2 = build_like(other, ar, donor_row=donor, index=mi)
    check(mf2.encode() == other_src,
          f"row {other} rebuilds byte-identically too, and its Water chunk is "
          f"NOT the donor's",
          f"{len(other_src)} B, {len(rep2.chunks)} chunks, "
          f"{rep2.pct(rep2.generated):.2f}% generated")
    check(rep2.substituted == (mapbuild.WATER_CHUNK,),
          "the report names the one borrowed chunk that was not a constant",
          f"substituted {[hex(c) for c in rep2.substituted]}, verified "
          f"{[hex(c) for c in rep2.verified]}")
    check(any("0x20000006" in n and "NOT a corpus constant" in n
              for n in rep2.notes),
          "and says so in words, so a reader of the report cannot miss it")
    water = next(c for c in rep2.chunks if c.chunk_id == mapbuild.WATER_CHUNK)
    check(f"row {other}" in water.how and "DISAGREED" in water.how,
          "the chunk's own provenance line names the row it really came from",
          water.how)
    check(len(rep2.verified) == 4,
          "the other four were corroborated by a different map this run",
          f"{[hex(c) for c in rep2.verified]}")


def main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__.strip().splitlines()[0],
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dat", default=None)
    ap.add_argument("--sample", type=int, default=6,
                    help="how many maps section 7 re-measures FINDINGS 14 over")
    args = ap.parse_args(argv)

    print(__doc__.strip().splitlines()[0])
    guarded(section0)
    guarded(section1)
    guarded(section2)
    guarded(section3)

    dat = args.dat or os.path.join(vaultpath.vault_path("dat_study"), "Gw.dat")
    if not os.path.isfile(dat):
        LEDGER.skip("everything that needs the archive (sections 4-8)",
                    f"no Gw.dat at {dat}; vault resolved to "
                    f"{vaultpath.vault_root()} ({vaultpath.vault_why()}). "
                    f"Sections 0-3 measured the builder against constants this "
                    f"test wrote and NOTHING about the byte-identity this rung "
                    f"is named for.")
        return LEDGER.verdict()

    with Archive(dat) as ar:
        mi = MapIndex(ar)
        rows = sorted(h.index for h in mi.heads)
        step = max(1, len(rows) // max(1, args.sample))
        picks = rows[::step][:args.sample]
        if TARGET_ROW not in picks:
            picks = [TARGET_ROW] + picks[:-1]
        got = guarded(section4, ar, mi)
        if got is None:
            return LEDGER.verdict()
        source, mf, _rep = got
        guarded(section5, ar, mi, source)
        guarded(section6, ar, mi, source, mf)
        guarded(section7, ar, mi, picks)
        guarded(section8, ar, mi, picks)
    return LEDGER.verdict()


if __name__ == "__main__":
    sys.exit(main())
