"""Energy and adrenaline, checked against retail's own property traffic.

`pools.py` is the arithmetic; this is where it meets the corpus. Section 2 is
the one that carries the module, and it is the shape `test_effects.py` section 2
established -- OUR DECODER CANNOT FORCE IT TRUE, because both inputs come from
outside:

    Join every property-43 (energy regeneration) event in the live corpus to
    that agent's OWN property-41 (maximum energy), and solve for pips:

        pips = rate * max / f32(0.33)

    All 52 must land on an INTEGER. Nothing was fitted: the rates and the maxima
    are retail's own f32s, the constant is a single number, and an integer is
    not what a wrong constant produces. The same section predicts all 45
    property-62 spends from the client's own energy-cost column; crosses every
    skill activation in the corpus against them and finds a 2x2 with TWO EMPTY
    CELLS (the observing player's own agent spends on all 45 of its paid casts
    and none of its 44 free ones, and 722 casts by other agents produce nothing
    at all); and confirms that property 33 -- an absolute "your energy is now
    N" -- appears zero times in 13,378 property messages while the positive
    control finds 97 and 52 of its neighbours in the same scan.

Section 1 is the discriminating negative: the NOMINAL rule that every source
states, one third of a point of energy per second, reproduces NONE of retail's
five rates, and the f32 constant 0.33 reproduces all five bit-exactly.

SECTION 11 IS THE ADRENALINE FAMILY ON THE WIRE, added 2026-08-21, and the
paragraph it replaces is worth keeping in view: this file used to assert that
"NOTHING about the adrenaline goes on the wire" because no upstream catalog
names an opcode for it. Four opcodes carry it -- 0x00CF/0x00D0/0x00D1/0x00D2 --
and retail sends three of them 724 times across the same 14 captures section 2
already reads. The section pins the byte widths against the CLIENT's own
declared sizes, the self-scope (an enemy's gain sends nothing), the measured
position of the spend (39 of 39 immediately before the property naming the
skill), the client's recharge skip with its own control, and the fact that 209
has a declaration and no send site.

SECTIONS 5-10 ARE THE GLUE, added the same day the wiring landed: `pools.py`
driven through `authsrv.py` itself, with a fake `send` and a hand-built
`state`, exactly the way `test_effects.py` 4d-4g drives the effect channel --
no socket, no client, no handshake. Section 5 is the one worth reading first,
because it does not test new code at all: it asserts that
`agents.PLAYER_FLOAT_43`, the 0.0396 this server has been sending since it was
copied out of gw-preservation with "purpose unknown upstream too" written
beside it, IS `wire_regen_rate(3, 25)` bit for bit -- three pips over a
25-energy pool, which is GWW's Ranger armour row, whose other half is the
`PLAYER_ENERGY` = 25 the same burst already sends. The magic number was a
measurement all along.

standard library only.

    python toolkit/authsrv/test_pools.py
"""
import os
import struct
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
sys.path.insert(0, os.path.join(os.path.dirname(HERE), "schema"))
import checks  # noqa: E402
import pools  # noqa: E402

# FLOOR 105, and it is the MANDATORY CORE rather than the full count, which is
# `checks.py`'s own instruction for a test whose count varies with the fixture:
# a real green run on this machine executes 121, and a run with no live captures
# executes 105 and declares the 16-check corpus oracle as a skip. Both numbers
# are from actual runs (2026-08-21, the second forced by making `_scan_corpus`
# raise), neither is a guess, and neither is above what a run produces. It was
# 40/56 before the glue sections 5-10 landed, and 82/98 before section 11 put
# the adrenaline family on the wire.
#
# THE GLUE SECTIONS ARE NOT IN THE SKIPPABLE HALF and that is deliberate: they
# read the client-table content overlay (`vault/content/skills.toml`) the same
# way `test_effects.py` section 3 does, and a machine without it should go RED
# here rather than quietly checking arithmetic. The overlay is regenerated by
# `skilltable.py --emit-content` from the owner's own install; the captures are
# not regenerable at all, which is why only they are declared skippable.
LEDGER = checks.Ledger("the energy and adrenaline pools", floor=108)

# The four generic-property opcodes, prop id FIRST in every one. 0x009F/0x00A2
# are the no-target int/float pair and 0x00A0/0x00A3 the with-target pair;
# `agents.py` (around line 1158) records how that pairing was CORROBORATED
# against the client's own dispatch table, where 0x009F and 0x00A0 forward to
# one handler and 0x00A2/0x00A3 to a different one.
INT_OPS = (0x009F, 0x00A0)
FLOAT_OPS = (0x00A2, 0x00A3)

PROP_ENERGY_MAX = 41
PROP_ENERGY_ABSOLUTE = 33       # the setter that does not exist -- see section 2

# The five (pips, max) pairs the corpus witnesses, plus (3, 30). WIKI (GWW,
# "Energy", rev. 2026-03-15) predicts them from the armour table: base 20
# energy / 2 pips, Warrior +0/+0, Ranger +1 pip/+5 energy, Dervish and Assassin
# +2/+5, casters +2/+10, hostile NPCs +1 pip.
#
# (3, 30) IS IN THIS LIST AND IS NOT WITNESSED, deliberately: it produces the
# same f32 as (2, 20) -- 0.033 -- so a check that only knows the RATE cannot
# tell the two apart. The join in section 2 can, and says all thirty of those
# events belong to agents whose own property-41 is 20. The degeneracy is why
# the join is worth doing at all.
CANDIDATE_PIPS = ((2, 20), (3, 25), (3, 30), (4, 25), (4, 30),
                  # THE MORALE-SCALED MAXIMA. Neither is an armour row:
                  # each is a base pool under a -15 death penalty, and the
                  # pip count is UNCHANGED across it, which is what makes
                  # them evidence rather than exceptions. 25 * 0.85 = 21.25
                  # -> 22 and 20 * 0.85 = 17, and the quantum reproduces
                  # both exactly -- so the denominator is CURRENT max, not
                  # base max (studies/skills section 23).
                  (4, 22), (2, 17))

# The SIX distinct nonzero property-43 f32s in the live corpus, with the count
# and the joined pair each one resolved to. OBSERVED 2026-08-20 over 14 captures;
# RE-COUNTED 2026-08-21 over 20, when the campaign's own new captures added the
# sixth. That sixth is the interesting one: 0.0388235 joins to (2 pips, 17 max),
# and 17 is 20 * 0.85 -- a Warrior's base pool under a -15 death penalty, with
# the SAME 2 pips. It is the second death-penalty witness for the quantum, from
# a different capture and a different base than the first ((4, 22), 20*0.85+5),
# and CONFIRMED 2026-08-22 rather than inferred: its connection carries
# 0x009C [observer, 85], so the morale is observed and not deduced from the 17.
# and it arrived as a test FAILURE: the armour-table check refused it because
# 17 is not an armour row. It was right to refuse and the model was right too --
# the pair is real, the quantum predicts it exactly, and what needed widening was
# the table's idea of which maxima are reachable.
RETAIL_RATES = {
    0.032999999821186066:  (2, 20, 40),
    0.038823530077934265:  (2, 17, 1),
    0.03959999978542328:   (3, 25, 4),
    0.04400000348687172:   (4, 30, 4),
    0.052800003439188004:  (4, 25, 11),
    0.06000000238418579:   (4, 22, 1),
}


def f32(x):
    return struct.unpack("<f", struct.pack("<f", x))[0]


def bits_to_f32(b):
    return struct.unpack("<f", struct.pack("<I", b & 0xFFFFFFFF))[0]


# ---------------------------------------------------------------------------


# The cast cycle the two refusal checks exist to forbid. Resolved lazily
# inside the helper because this module imports `authsrv` further down.
def refusal_shape(sent):
    """(ops sent, whether they are exactly retail's measured refusal batch).

    THE BATCH IS MEASURED, not chosen: 43 of 143 corpus presses are declined,
    43 of 43 are answered, and 40 of 40 carry
    [0x005D CHAT_MESSAGE_CORE, 0x005E CHAT_MESSAGE_SERVER ch7, 0x00E2] in that
    order with nothing between them. The other 3 send the bare 0x00E2.
    """
    import authsrv
    ops = [op for op, _v, _w in sent]
    return ops, ops == [authsrv.GAME_SMSG_CHAT_MESSAGE_CORE,
                        authsrv.GAME_SMSG_CHAT_MESSAGE_SERVER,
                        authsrv.GAME_SMSG_SKILL_REFUSED]


def cast_cycle_ops():
    """A refusal may send the refusal batch and NOTHING from this set."""
    import authsrv
    return {authsrv.GAME_SMSG_SKILL_ACTIVATED_BROADCAST,   # 0x00E4
            authsrv.GAME_SMSG_SKILL_ACTIVATED,             # 0x00E3
            authsrv.GAME_SMSG_SKILL_RECHARGE,              # 0x00E5
            authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_FLOAT} # the 62 debit


def section_quantum():
    """THE QUANTUM: 0.33 as an f32, against the 1/3 every source states.

    Five bit patterns, one check each, so a failure names the cluster that
    moved. Then the negative that makes them mean something.
    """
    print("1. the quantum -- f32(0.33)*pips/max, bit for bit")

    for rate, (pips, mx, n) in sorted(RETAIL_RATES.items()):
        got = pools.wire_regen_rate(pips, mx)
        LEDGER.ok(got == rate,
                  f"{pips} pips over {mx} energy is exactly {rate!r}",
                  f"got {got!r}; retail sent this f32 {n} time(s). Compared "
                  f"with == and not a tolerance -- an f32 the client stores and "
                  f"animates from either matches or does not")

    nominal = [f32(p / (3.0 * m)) for p, m, _n in RETAIL_RATES.values()]
    LEDGER.ok(not (set(nominal) & set(RETAIL_RATES)),
              "and the NOMINAL 1/3 energy per second reproduces NONE of the five",
              f"{[round(x, 8) for x in nominal]} against "
              f"{[round(x, 8) for x in sorted(RETAIL_RATES)]}. Every source "
              f"states a pip as one third of a point per second; the client's "
              f"constant is 0.33f. 1% of the regeneration rate, which is 40 "
              f"seconds of energy over a 20-minute run -- and, more usefully, "
              f"a difference our own captures can SEE")

    as_double = sum(1 for rate, (p, m, _n) in RETAIL_RATES.items()
                    if f32(0.33 * p / m) == rate)
    LEDGER.ok(as_double < len(RETAIL_RATES),
              "and 0.33 as a DOUBLE misses some of them -- the constant is a float",
              f"{as_double} of {len(RETAIL_RATES)} match when 0.33 is not "
              f"rounded to f32 first. That is the evidence for `float` rather "
              f"than `double` in the client, and it is the whole reason "
              f"`wire_regen_rate` rounds the constant before it multiplies")

    LEDGER.ok(pools.wire_regen_rate(3, 25) == f32(0.0396),
              "and this finally EXPLAINS content/world.toml's float_43 = 0.0396",
              "3 pips over a 25-energy pool. That constant was copied from "
              "gw-preservation, whose own comment says 'REVERSE THIS MORE', and "
              "`agents.py` records it as a GUESS. It is a ranger's regeneration "
              "on a ranger's pool, it is internally consistent with "
              "PLAYER_ENERGY = 25, and it is now a measured value rather than "
              "an inherited one")

    LEDGER.ok(pools.wire_regen_rate(0, 25) == 0.0,
              "zero pips is exactly 0.0, which is what a death sends",
              "OBSERVED twice: property 43 goes to 0.0 in the same batch as the "
              "death bit, once at max 25 and once at max 22")
    try:
        pools.wire_regen_rate(2, 0)
        refused = None
    except pools.PoolError as ex:
        refused = str(ex)
    LEDGER.ok(refused is not None,
              "and a pool of zero REFUSES rather than dividing",
              "the rate is a fraction OF THE POOL; an inf reinterpreted into "
              "the dword slot is a number the client will animate towards")

    print("\n1b. the property ids agree with the server's own vocabulary")
    try:
        import agents
        same = (pools.GV_ENERGY_GAIN == agents.GV_ENERGY_GAIN
                and pools.GV_ENERGY_SPENT == agents.GV_ENERGY_SPENT
                and pools.GV_ENERGY_REGEN == agents.PROP_UNKNOWN_FLOAT_43)
        LEDGER.ok(same,
                  "52, 62 and 43 match agents.py's declarations",
                  f"{pools.GV_ENERGY_GAIN}/{pools.GV_ENERGY_SPENT}/"
                  f"{pools.GV_ENERGY_REGEN}. They are restated in pools.py "
                  f"rather than imported so the module keeps effects.py's "
                  f"property of importing nothing from the server -- which "
                  f"leaves exactly one way for the two copies to drift, and "
                  f"this is it")
    except Exception as ex:                                    # noqa: BLE001
        LEDGER.skip("the id cross-check", f"agents.py unavailable ({ex})")


# ---------------------------------------------------------------------------


def _scan_corpus():
    """Every generic-property event in the live corpus, joined per agent.

    Returns (totals, regen_rows, spend_rows, gain_values, cast_rows). Each
    regen and spend row carries the agent's own most recent property-41 maximum
    -- the join that makes the integrality check possible -- and each spend also
    carries the skill it belongs to. Each cast row says whether that agent ever
    received a property 41 in this connection (`own`) and whether a property 62
    rode the same batch (`spend`), which is what section 2e's contingency table
    is built from.

    THE CAST JOIN IS BY TIME AND NOT BY STREAM ORDER, and that cost a red run
    before it was written down. A property-62 spend and the property-60/50/48
    that names the skill ride the SAME BATCH (lag 0.000 s for 45 of 45), and the
    SPEND COMES FIRST in the stream, also 45 of 45. So the streaming reading --
    "attribute a spend to the last cast already seen" -- attributes every single
    one to the PREVIOUS cast, and scores 18 of 45 with a plausible-looking mix
    of zero-cost skills in the miss list. Joining on `cast_t <= spend_t` instead
    scores 45 of 45. Section 2c checks the ordering itself so this stays a
    measured fact rather than a comment.
    """
    import tape
    import vaultpath
    from codec import Codec

    live = vaultpath.require_dir("captures", "live",
                                 why="the energy-property oracle")
    codec = Codec()
    totals = {"messages": 0, "props": {}, "captures": 0, "orphans": 0,
              "spend_first": 0, "cast_first": 0, "lags": set(),
              "p41_seqs": {}, "own_agents": 0}
    regen, spends, gains, cast_rows = [], [], [], []
    CAST_PROPS = {48, 50, 60}       # instant, attack-skill, skill activated

    for stamp in sorted(os.listdir(live)):
        cap = os.path.join(live, stamp)
        if not os.path.isdir(cap):
            continue
        totals["captures"] += 1
        for conn in tape.channel_files(cap):
            try:
                info, events = tape.load_tape(cap, conn["connection"])
                msgs, _receipt = tape.decode_all(events, codec, "GAME_SMSG", 0)
            except Exception:                                  # noqa: BLE001
                continue
            emax, casts, pending, seqs = {}, [], [], {}
            for i, (t, op, v) in enumerate(msgs):
                if op not in INT_OPS and op not in FLOAT_OPS:
                    continue
                prop, agent = v[1], v[2]
                totals["messages"] += 1
                totals["props"][prop] = totals["props"].get(prop, 0) + 1
                if op in INT_OPS and prop == PROP_ENERGY_MAX:
                    emax[agent] = v[-1]
                    seqs.setdefault(agent, []).append(v[-1])
                elif op in INT_OPS and prop in CAST_PROPS:
                    casts.append((i, t, agent, v[-1]))
                elif op in FLOAT_OPS and prop == pools.GV_ENERGY_REGEN:
                    if agent not in emax:
                        totals["orphans"] += 1
                    regen.append({"stamp": stamp, "agent": agent,
                                  "rate": bits_to_f32(v[-1]),
                                  "max": emax.get(agent)})
                elif op in FLOAT_OPS and prop == pools.GV_ENERGY_SPENT:
                    pending.append((i, t, agent, bits_to_f32(v[-1]),
                                    emax.get(agent)))
                elif op in FLOAT_OPS and prop == pools.GV_ENERGY_GAIN:
                    gains.append({"stamp": stamp, "agent": agent,
                                  "value": bits_to_f32(v[-1])})
            for i, t, agent, value, mx in pending:
                prior = [c for c in casts if c[2] == agent and c[1] <= t + 1e-9]
                ci, ct, _a, skill = prior[-1] if prior else (None, None, None, None)
                if ci is not None:
                    totals["lags"].add(round(t - ct, 6))
                    totals["spend_first" if ci > i else "cast_first"] += 1
                spends.append({"stamp": stamp, "agent": agent, "value": value,
                               "max": mx, "skill": skill})

            paid_batches = {(round(t, 6), agent) for _i, t, agent, _v, _m in pending}
            for _i, t, agent, skill in casts:
                cast_rows.append({"stamp": stamp, "agent": agent,
                                  "skill": skill, "own": agent in emax,
                                  "spend": (round(t, 6), agent) in paid_batches})
            for agent, seq in seqs.items():
                totals["own_agents"] += 1
                key = tuple(seq)
                totals["p41_seqs"][key] = totals["p41_seqs"].get(key, 0) + 1
    return totals, regen, spends, gains, cast_rows


def section_corpus_oracle():
    """RETAIL'S OWN PROPERTY TRAFFIC, predicted with no free parameter."""
    print("\n2. the live corpus: does f32(0.33) predict retail's energy?")
    try:
        import content
        totals, regen, spends, gains, cast_rows = _scan_corpus()
        world = content.load()
    except (Exception, SystemExit) as ex:                      # noqa: BLE001
        # SystemExit is deliberate and not defensive: `vaultpath.require_dir`
        # raises SystemExit by design, and it is NOT an Exception subclass -- a
        # bare `except Exception` here would let a missing vault kill the run
        # with a traceback and exit 1 instead of declaring the skip that the
        # floor rule is built around. A crash and a skip look nothing alike to
        # a reader and identical to a CI exit code.
        LEDGER.skip("the live-corpus energy oracle",
                    f"no vault captures or no content overlay here ({ex}). "
                    f"This is the section that carries the module -- a green "
                    f"run without it has checked the arithmetic and none of "
                    f"the evidence")
        return

    LEDGER.ok(totals["messages"] >= 13000 and totals["captures"] >= 14,
              f"the corpus still holds {totals['messages']} property messages "
              f"over {totals['captures']} captures",
              "13,378 over 14 when this was written. A corpus that shrank is a "
              "vault that moved, and every count below would quietly get easier")

    print("\n2a. there is NO absolute energy setter -- and the control passes")
    LEDGER.ok(totals["props"].get(PROP_ENERGY_ABSOLUTE, 0) == 0,
              f"property 33 appears 0 times in {totals['messages']} property "
              f"messages",
              "the obvious 'your energy is now N' does not exist on the wire. "
              "So the client INTEGRATES energy itself from max + rate + "
              "deltas, and a server that sends no deltas leaves the orb flat -- "
              "which is exactly what two harness runs on 2026-08-20 show, at 25 "
              "through eight presses including Flare")
    LEDGER.ok(totals["props"].get(PROP_ENERGY_MAX, 0) >= 90
              and len(regen) >= 50,
              f"POSITIVE CONTROL: the same scan finds "
              f"{totals['props'].get(PROP_ENERGY_MAX, 0)} property-41s and "
              f"{len(regen)} property-43s",
              "a filtered search that finds nothing proves nothing until it has "
              "found something we already know it should. 97 and 52 when this "
              "was written")

    print("\n2b. every regeneration rate, joined to its own agent's maximum")
    LEDGER.ok(totals["orphans"] == 0,
              f"all {len(regen)} property-43 events join to a property-41",
              "an unjoined rate would have to be dropped, and a check that "
              "silently drops its awkward rows is the check this repo keeps "
              "catching itself building")

    quantum = f32(pools.PIP_ENERGY_PER_SECOND)
    non_integer, seen = [], {}
    for r in regen:
        if r["max"] is None:
            continue
        pips = r["rate"] * r["max"] / quantum
        if abs(pips - round(pips)) > 1e-6:
            non_integer.append((r["stamp"], r["rate"], r["max"], pips))
        key = (int(round(pips)), r["max"])
        seen[key] = seen.get(key, 0) + 1
    LEDGER.ok(not non_integer,
              f"and pips = rate x max / f32(0.33) is an INTEGER for all "
              f"{len(regen)} of them",
              f"{dict(sorted(seen.items()))} -- (pips, max) -> n. THE CHECK "
              f"WITH NO FREE PARAMETER: the rates and the maxima are retail's "
              f"own f32s and the constant is one number, so a wrong constant "
              f"has no reason to produce integers at all. Non-integers: "
              f"{non_integer[:3]}")

    LEDGER.ok(set(seen) - {(0, 17), (0, 20), (0, 22), (0, 25), (0, 30)}
              <= set(CANDIDATE_PIPS),
              "and every pair is an armour row or a morale-scaled one",
              f"{sorted(k for k in seen if k[0])}. WIKI (GWW, 'Energy', rev. "
              f"2026-03-15): base 20/2, Warrior +0/+0, Ranger +1 pip/+5, "
              f"Dervish and Assassin +2/+5, casters +2/+10. (2,20) is a "
              f"warrior, (3,25) a ranger, (4,25) a dervish or assassin, (4,30) "
              f"a caster. The zero-pip rows are deaths, and (4,22) and (2,17) "
              f"are DEATH-PENALTY maxima carrying their base pip count "
              f"unchanged, which is why the denominator has to be current max "
              f"rather than base max. THE ARITHMETIC WAS WRONG HERE UNTIL "
              f"2026-08-22: this said 25*0.85 for the 22, which is 21.25 and "
              f"not an integer. Morale scales the BASE pool only and armour "
              f"bonuses ride unscaled -- the morale arc's own rule, from the "
              f"one instrumented death (studies/morale) -- so 22 is "
              f"20*0.85 + 5 (a dervish or assassin) and 17 is 20*0.85 + 0 (a "
              f"warrior). Both now have their morale DIRECTLY OBSERVED: each "
              f"of those two connections carries 0x009C [observer, 85]")

    LEDGER.ok(seen.get((2, 20), 0) >= 30 and not any(
                  k[0] == 3 and k[1] == 30 for k in seen),
              "the 0.033 DEGENERACY resolves to 2 pips over 20, all 30 times",
              f"{seen.get((2, 20), 0)} at (2,20) and "
              f"{sum(n for k, n in seen.items() if k == (3, 30))} at (3,30). "
              f"2/20 and 3/30 are the same f32, so the rate alone cannot "
              f"separate them and the JOIN can. This is the whole reason the "
              f"oracle reads property 41 rather than pattern-matching floats")

    distinct = {r["rate"] for r in regen if r["rate"]}
    predicted = {pools.wire_regen_rate(p, m) for p, m in CANDIDATE_PIPS}
    LEDGER.ok(distinct <= predicted and len(distinct) >= 6,
              f"all {len(distinct)} distinct nonzero rates are predicted values",
              f"{sorted(distinct)} -- and the seven candidate pairs generate "
              f"only {len(predicted)} distinct f32s, because 2/20 and 3/30 "
              f"collide. Unpredicted: {sorted(distinct - predicted)}")

    print("\n2c. every discrete spend, against the client's own cost column")
    misses, hits, by_skill = [], 0, {}
    for s in spends:
        if s["skill"] is None or s["max"] is None:
            misses.append((s["stamp"], "unjoined", s["value"]))
            continue
        try:
            cost = int(world.get("skills", str(s["skill"]))["energy"])
        except Exception:                                      # noqa: BLE001
            misses.append((s["stamp"], f"no row for {s['skill']}", s["value"]))
            continue
        want = f32(pools.spend_fraction(cost, s["max"]))
        _c, _m, n = by_skill.get(s["skill"], (cost, s["max"], 0))
        by_skill[s["skill"]] = (cost, s["max"], n + 1)
        if want == s["value"]:
            hits += 1
        else:
            misses.append((s["skill"], cost, s["max"], s["value"], want))
    LEDGER.ok(not misses and hits >= 45,
              f"{hits} of {len(spends)} property-62 spends predicted EXACTLY, "
              f"{len(misses)} missed",
              f"-(energy_cost / max_energy), over "
              f"{len(by_skill)} skills: {dict(sorted(by_skill.items()))} as "
              f"skill -> (cost, max, n). The costs are the client's own +0x35 "
              f"column and the maxima are retail's property 41; nothing was "
              f"fitted. Misses: {misses[:3]}")

    fixed = sum(1 for s in spends
                if s["skill"] is not None and s["max"] is not None
                and f32(pools.spend_fraction(
                    int(world.get("skills", str(s["skill"]))["energy"]), 20))
                != s["value"])
    LEDGER.ok(fixed > 0,
              f"CONTROL: a FIXED denominator of 20 misses {fixed} of "
              f"{len(spends)}",
              "so the check above is discriminating rather than agreeing with "
              "whatever it is handed. The fraction really is over the agent's "
              "own pool: 5 energy is -0.25 on a 20-pool and -0.2 on a 25-pool, "
              "and both appear")

    LEDGER.ok(totals["lags"] == {0.0}
              and totals["spend_first"] == len(spends)
              and totals["cast_first"] == 0,
              f"and the spend rides the SAME BATCH as the activation, BEFORE it, "
              f"{totals['spend_first']} of {len(spends)}",
              f"lags {sorted(totals['lags'])}, spend-first "
              f"{totals['spend_first']} / cast-first {totals['cast_first']}. "
              f"MEASURED because the first version of this section got it "
              f"wrong: attributing each spend to the last cast ALREADY SEEN "
              f"scored 18 of 45 and filled the miss list with zero-cost skills, "
              f"which looks like a modelling error and was an ordering one. It "
              f"also tells the sender what to do -- retail emits property 62 "
              f"and THEN the property-60 that names the skill")

    print("\n2d. WHO gets a property 62, and for WHICH casts -- the whole 2x2")
    table = {}
    for c in cast_rows:
        try:
            cost = int(world.get("skills", str(c["skill"]))["energy"])
        except Exception:                                      # noqa: BLE001
            continue
        key = ("own" if c["own"] else "other",
               "paid" if cost else "free",
               "spend" if c["spend"] else "silent")
        table[key] = table.get(key, 0) + 1
    own_paid_spend = table.get(("own", "paid", "spend"), 0)
    own_paid_silent = table.get(("own", "paid", "silent"), 0)
    own_free_spend = table.get(("own", "free", "spend"), 0)
    own_free_silent = table.get(("own", "free", "silent"), 0)
    other_spend = sum(n for k, n in table.items()
                      if k[0] == "other" and k[2] == "spend")
    other_silent = sum(n for k, n in table.items()
                       if k[0] == "other" and k[2] == "silent")

    LEDGER.ok(other_spend == 0 and other_silent > 700,
              f"property 62 is the OBSERVING PLAYER'S OWN agent alone -- "
              f"{other_silent} casts by other agents, {other_spend} spends",
              "579 paid casts and 143 free ones by agents that never receive a "
              "property 41, and NOT ONE carries a spend. So the energy channel "
              "is scoped to the agent whose orb is on screen, and 'one property "
              "62 per cast' would have been the wrong rule to build a server on "
              "-- our own enemies must not emit one")
    LEDGER.ok(own_paid_silent == 0 and own_paid_spend >= 45,
              f"and for THAT agent every PAID cast carries one: "
              f"{own_paid_spend} of {own_paid_spend + own_paid_silent}",
              "no exceptions in either direction, which is what makes 'once per "
              "completed cast' a rule rather than a tendency")
    LEDGER.ok(own_free_spend == 0 and own_free_silent >= 44,
              f"while its {own_free_silent} ZERO-COST casts carry NONE",
              f"{own_free_silent} of {own_free_silent} silent. This is the "
              f"measurement behind `spend()` returning None rather than 0.0, "
              f"and it is the OTHER empty cell -- a 2x2 with two zeros is a "
              f"rule; one zero would only be a tendency")

    LEDGER.ok(all(seq[0] == 1 for seq in totals["p41_seqs"])
              and totals["own_agents"] >= 48,
              f"OBSERVED, unexplained: property 41 arrives as (1, real_max) for "
              f"all {totals['own_agents']} own agents",
              f"{ {seq: n for seq, n in sorted(totals['p41_seqs'].items(), key=str)} }"
              f" -- 30 warriors at (1,20), 13 at (1,25), 4 at (1,30) and one "
              f"(1,25,22), which is agent 27 taking the death penalty. WHY the "
              f"leading 1 is there is NOT FOUND and nothing here reads it; it is "
              f"recorded because our own spawn sends a single property 41 and "
              f"retail sends two, which is a difference a client run can see")

    print("\n2f. and the gains we have")
    gain_value = gains[0]["value"] if gains else None
    # n WENT FROM 1 TO 2 on 2026-08-21, when the campaign's own captures
    # added a second resurrect. The assertion is on the VALUE and only a
    # FLOOR on the count, for exactly that reason: a fresh capture must be
    # able to add a witness without turning this red, while a gain that is
    # not 1.0 must still fail. Zero gains means the scan broke.
    LEDGER.ok(len(gains) >= 1 and all(g["value"] == 1.0 for g in gains),
              f"property 52 appears {len(gains)} time(s), each with the value "
              f"{gain_value!r}",
              f"{gains} -- a resurrect, in the batch where the death bit clears, "
              f"property 43 returns to the agent's rate and property 55 (the "
              f"health half) also carries exactly 1.0. n=1 is n=1: `refill` "
              f"returns this number and claims nothing about partial gains, "
              f"which the corpus never witnesses")


# ---------------------------------------------------------------------------


def section_energy_pool():
    """The pool itself: full at spawn, integrates the wire's own rate, pays."""
    print("\n3. EnergyPool -- integrate the number we actually sent")
    p = pools.EnergyPool(25, 3, now=1000.0)
    LEDGER.ok(p.current == 25.0,
              "a pool starts FULL",
              "OBSERVED: property 41 arrives at agent create and nothing "
              "follows it, so the client's orb is full from the first frame")
    LEDGER.ok(p.rate == f32(0.0396),
              "and carries the f32 to put on property 43 as a field",
              f"{p.rate!r} -- so the sender reads it rather than recomputing it, "
              f"and the number the server integrates is the number the client "
              f"was told")

    p.current = 0.0
    gained = p.tick(1001.0)
    LEDGER.ok(abs(gained - 0.99) < 1e-6 and abs(p.current - 0.99) < 1e-6,
              "one second at 3 pips over 25 energy is 0.99 energy",
              f"{gained!r}. 3 x 0.33. The integration uses rate x maximum -- "
              f"the wire value -- rather than pips x 0.33, so the server and "
              f"the orb cannot drift apart over a long session")
    p.current = 24.9
    gained = p.tick(1002.0)
    LEDGER.ok(p.current == 25.0 and abs(gained - 0.1) < 1e-6,
              "and it CLAMPS at the maximum, returning what the pool took",
              f"gained {gained!r} of the 0.99 the second was worth. A tick that "
              f"reports the elapsed value would overstate every full pool")
    LEDGER.ok(p.tick(1003.0) == 0.0 and p.tick(1002.0) == 0.0,
              "a full pool gains nothing, and so does a clock going backwards",
              "the second is not hypothetical: the world tick and a connection "
              "thread both reach this, and a negative dt would DRAIN the pool")

    print("\n3b. paying for a cast")
    q = pools.EnergyPool(20, 2, now=0.0)
    LEDGER.ok(q.can_pay(5) and not q.can_pay(21),
              "can_pay answers against the current level, not the maximum")
    LEDGER.ok(q.spend(5) == -0.25 and q.current == 15.0,
              "spending 5 from a 20-pool is -0.25 -- retail's own number for "
              "skill 364",
              "27 of the corpus's 45 property-62 events are exactly this: "
              "Flare-class 5-energy skills on a 20-energy warrior")
    LEDGER.ok(pools.EnergyPool(25, 4).spend(5) == -0.2,
              "and 5 from a 25-pool is -0.2, which is also retail's",
              "skills 780, 814 and 858, 11 events. The SAME cost produces a "
              "different fraction on a different pool, which is what makes the "
              "denominator load-bearing")
    LEDGER.ok(q.spend(0) is None,
              "a ZERO-cost skill returns None, not 0.0",
              "44 of 44 zero-cost casts in the corpus send no property 62 at "
              "all. None makes the caller send nothing; 0.0 would be a message "
              "retail never sends and -0.0 would read as a spend in every log")
    try:
        q.spend(999)
        refused = None
    except pools.PoolError as ex:
        refused = str(ex)
    LEDGER.ok(refused is not None and q.current == 15.0,
              "and an unpayable cost RAISES, leaving the pool untouched",
              "the caller checks can_pay() and declines the cast where it can "
              "also tell the client why. A pool that part-paid would put the "
              "orb and the server permanently out of step -- and with no "
              "absolute setter on the wire, that is not correctable afterwards")

    print("\n3c. death, the penalty, and coming back")
    r = pools.EnergyPool(25, 4, now=0.0)
    LEDGER.ok(r.rate == 0.052800003439188004,
              "agent 27 of capture 20260817T183756 ran at 0.0528 with max 25",
              "four pips on a dervish or assassin pool")
    LEDGER.ok(r.set_maximum(22) == 0.06000000238418579,
              "and after the death penalty took it to 22, retail re-sent 0.06",
              f"{r.rate!r} -- the SAME four pips over the NEW denominator. That "
              f"is the one witness for 'the denominator is the CURRENT max', "
              f"and it is why set_maximum recomputes instead of clamping")
    r.current = 3.0
    LEDGER.ok(r.refill() == 1.0 and r.current == 22.0,
              "a resurrect refills the pool and reports a gain of 1.0",
              "OBSERVED once, in that same capture's resurrect batch")


# ---------------------------------------------------------------------------


BAR = {317: 80, 318: 120, 319: 80, 382: 100}
# The four adrenal skills on our own default bar, in RAW UNITS from the client
# table's +0x38 -- Battle Rage, Defy Pain, Rush, Sever Artery. The client
# DISPLAYS ceil(units/25), i.e. 4, 5, 4, 4 (`clientscan/skilltable.py:180`), and
# `vault/content/skills.toml` currently carries only that displayed column.


def section_adrenaline_pool():
    """Strikes, the floor on damage gain, and the 25-second forgetting."""
    print("\n4. AdrenalinePool -- raw units, one pool per skill")
    a = pools.AdrenalinePool(BAR)
    a.on_hit_landed(0.0)
    LEDGER.ok(all(a.units[s] == 25 for s in BAR),
              "one landed hit is 25 units into EVERY pool at once",
              "WIKI (GWW, 'Adrenaline', rev. 2026-07-02): a strike is 25 units "
              "and all adrenal skills charge simultaneously")

    print("\n4b. Battle Rage: 3 strikes and 5 units, verbatim")
    b = pools.AdrenalinePool({317: 80})
    b.on_hit_landed(1.0)
    b.on_hit_landed(2.0)
    b.on_hit_landed(3.0)
    LEDGER.ok(b.units[317] == 75 and not b.charged(317),
              "three hits is 75 units and Battle Rage is NOT charged",
              "it costs 80 RAW units. The icon says 4, which is ceil(80/25), "
              "and a server that compared against 4 strikes would demand 100 "
              "and leave the skill dark through a fight it should have fired in")
    newly = b.on_damage_taken(0.05, 4.0)
    LEDGER.ok(b.units[317] == 80 and b.charged(317) and newly == [317],
              "5% of maximum health taken is the last 5 units, and it charges",
              "GWW's own Notes on Battle Rage: 'exactly requires 80 units of "
              "adrenaline (3 strikes and 5 units)'. This is that sentence, as "
              "arithmetic, with the raw cost coming from the client's +0x38")

    print("\n4c. the gain from damage is FLOORED, and zero is not combat")
    c = pools.AdrenalinePool({319: 80})
    c.on_hit_landed(0.0)
    # 0.2%, NOT 0.7%. Re-pinned 2026-08-21 when the corpus refuted the wiki's
    # floored rule (see `damage_units`): rounding puts the no-grant boundary at
    # 0.5%, so 0.7% now grants ONE unit and is no longer a no-op. The check
    # still needs a genuinely 0-unit event to make its point, and 0.2% is one
    # under either rule -- which is why it was chosen over a value that only
    # works under the new one.
    LEDGER.ok(c.on_damage_taken(0.002, 5.0) == [] and c.units[319] == 25,
              "0.2% of maximum health grants NOTHING",
              "one unit per 1% lost, ROUNDED (31/31 of the corpus join). A "
              "stream of scratches must "
              "not charge a bar")
    LEDGER.ok(c.tick(26.0) is True and c.units[319] == 0,
              "and that no-op did NOT refresh the combat clock -- 26 s wipes",
              "WIKI: zero damage 'does not count as being in combat'. The hit "
              "was at t=0, the scratch at t=5, and the bar is gone at t=26. "
              "Touching the clock on a 0-unit event would keep a bar charged "
              "forever off harmless pings")
    d = pools.AdrenalinePool({319: 80})
    d.on_hit_landed(0.0)
    d.on_damage_taken(0.05, 5.0)
    LEDGER.ok(d.tick(26.0) is False and d.units[319] == 30,
              "CONTROL: a REAL damage gain at t=5 does refresh it",
              f"{d.units[319]} units still there at t=26. So the check above "
              f"discriminates between two outcomes rather than agreeing with "
              f"whatever it is handed")
    LEDGER.ok(d.tick(31.0) is True and d.tick(32.0) is False,
              "and the timeout reports True exactly ONCE",
              "the caller logs a real event on the wipe; a tick that kept "
              "returning True would log a heartbeat")

    print("\n4d. using one: own pool to zero, everyone else down a strike")
    e = pools.AdrenalinePool(BAR)
    for i in range(4):
        e.on_hit_landed(float(i))
    LEDGER.ok(e.units == {317: 80, 318: 100, 319: 80, 382: 100},
              "four hits: 100 units, CAPPED at each skill's own cost",
              "80 for Battle Rage and Rush, 100 for Defy Pain (which costs 120) "
              "and Sever Artery (which costs 100). RECONSTRUCTION -- GWW states "
              "the gain and the cost but never the surplus; capping is the "
              "conservative direction, because an uncharged overflow would let "
              "one long fight fire a skill twice")
    LEDGER.ok(e.charged(317) and e.charged(382) and not e.charged(318),
              "so three of the four are charged and Defy Pain is not",
              "120 raw units, displayed as 5")
    e.use(317)
    LEDGER.ok(e.units[317] == 0,
              "using Battle Rage zeroes ITS pool")
    LEDGER.ok(e.units == {317: 0, 318: 75, 319: 55, 382: 75},
              "and costs every OTHER pool exactly one strike",
              "WIKI: 'whether or not the skill is interrupted or fails' -- so "
              "this fires at USE and not on completion, which is the opposite "
              "of the energy spend, and the corpus shows property 62 landing "
              "once per COMPLETED cast")
    e.use(319)
    LEDGER.ok(e.units[319] == 0 and e.units[317] == 0,
              "and a decrement FLOORS at zero rather than going negative",
              f"{e.units} -- 317 was already empty and stays empty")

    print("\n4e. death, and a bar with nothing adrenal on it")
    f = pools.AdrenalinePool(BAR)
    f.on_hit_landed(0.0)
    f.clear()
    LEDGER.ok(not any(f.units.values()) and f.tick(100.0) is False,
              "death clears every pool AND forgets the combat clock",
              "WIKI: all adrenaline is lost on death. Forgetting the clock is "
              "what stops the next tick reporting a timeout wipe for a bar a "
              "death already emptied")
    g = pools.AdrenalinePool({105: 0, 153: 0})
    LEDGER.ok(g.costs == {} and g.units == {},
              "a bar of pure energy skills makes an INERT pool, not four zeros",
              "only entries with units > 0 are tracked, so `{}` is legal and a "
              "caster's bar costs nothing to carry")
    g.on_hit_landed(0.0)
    LEDGER.ok(g.charged(105) is False,
              "an inert pool charges nothing and answers False",
              "a skill with no adrenaline cost is never `charged` -- the "
              "question does not apply to it")
    try:
        g.use(105)
        refused = None
    except pools.PoolError as ex:
        refused = str(ex)
    LEDGER.ok(refused is not None,
              "and USING a non-adrenal skill through this pool REFUSES",
              "the alternative is a caller that wires every keypress here and "
              "quietly drains three pools every time the player casts a spell")


# --------------------------------------------------------------- the glue
#
# Sections 1-4 are the arithmetic and the corpus. Everything below is the
# SERVER: `pools.py` wired into `authsrv.py`, driven through a fake `send` and
# a hand-built `state` exactly the way `test_effects.py` sections 4d-4g drive
# the effect channel. No socket, no client, no handshake -- the whole point of
# extracting `handle_skill_press` from the dispatch chain in the first place.


def fake():
    """(sent, send, state) -- the three things every glue section starts with."""
    sent = []
    send = lambda op, vals, why="": sent.append((op, vals, why))    # noqa: E731
    return sent, send, {"agents": {}}


def props(sent, opcode, prop):
    """Every value list on `opcode` carrying property id `prop`."""
    return [v for op, v, _w in sent if op == opcode and v and v[0] == prop]


def section_constants():
    """The two constants this server already sent, now EXPLAINED.

    `agents.PLAYER_FLOAT_43` has been 0.0396 since it was copied out of
    gw-preservation's `sendPlayerAttributes`, and the send that carries it says
    "purpose unknown upstream too" in its own comment. It is not unknown any
    more, and this section is the identity that says so -- bit for bit, not to
    seven digits.
    """
    print("\n5. the server's own magic number, read back as three pips")
    import authsrv
    import agents

    predicted = pools.wire_regen_rate(authsrv.PLAYER_ENERGY_PIPS,
                                      agents.PLAYER_ENERGY)
    LEDGER.ok(predicted == f32(agents.PLAYER_FLOAT_43),
              "PLAYER_FLOAT_43 IS wire_regen_rate(3, 25), exactly",
              f"{predicted!r} against {f32(agents.PLAYER_FLOAT_43)!r} -- the "
              f"constant gw-preservation shipped as a magic number is three "
              f"pips over a 25-energy pool, which WIKI (GWW, 'Energy', rev. "
              f"2026-03-15) gives as the RANGER armour row (base 20/2, Ranger "
              f"+1 pip and +5 energy). Two constants this server already sent "
              f"agree with the armour table and with each other")
    LEDGER.ok(agents.PLAYER_ENERGY == 25,
              "and the other half of that row is the maximum we already send",
              f"{agents.PLAYER_ENERGY} -- property 41 at spawn")
    LEDGER.ok(authsrv.GV_ENERGY_REGEN == pools.GV_ENERGY_REGEN
              == agents.PROP_UNKNOWN_FLOAT_43 == 43,
              "and all three names for property 43 are the same number",
              f"{authsrv.GV_ENERGY_REGEN}/{pools.GV_ENERGY_REGEN}/"
              f"{agents.PROP_UNKNOWN_FLOAT_43}. `agents.py` still calls it "
              f"UNKNOWN_FLOAT_43; the corpus named it and the alias is kept "
              f"rather than renamed under the spawn send that uses it")

    enemy = pools.EnergyPool(authsrv.ENEMY_ENERGY, authsrv.ENEMY_ENERGY_PIPS)
    LEDGER.ok(abs(enemy.energy_per_second() - 1.65) < 0.01,
              "the hostile's 5 pips over 30 energy is 1.65 energy a second",
              f"{enemy.energy_per_second():.4f}. RECONSTRUCTION on the "
              f"profession half: WIKI gives casters +2 pips/+10 energy over "
              f"the 20/2 base and hostile NPCs 'an additional pip', so 4+1 "
              f"over 30 is a hostile caster -- which is what our standing "
              f"agent's own bar (Restore Condition, Scourge Sacrifice, Holy "
              f"Strike, Vital Blessing) reads as. Nothing on the wire declares "
              f"an NPC's profession to us")


def section_gate():
    """The gate and the debit, through `handle_skill_press` itself.

    THE DEBIT IS THE MEASURED HALF: property 62 on `0x00A2`, value
    -(cost / max) as an f32, one per paid cast and NOTHING for a free one (44
    of 44 in the corpus). THE REFUSAL IS OURS -- what retail's server does with
    an unaffordable press is unobserved, and the client may never send one --
    so what is checked here is that the refusal is TOTAL: no E4, no animation,
    no pending cast, nothing for the client to have to un-draw.
    """
    print("\n6. pressing a skill: the gate, then the debit")
    import authsrv
    import agents

    sent, send, state = fake()
    authsrv.handle_skill_press([0, 194, 0, 0], send, state, 0,
                               authsrv.GAME_CMSG_USE_SKILL)
    spends = props(sent, authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_FLOAT,
                   agents.GV_ENERGY_SPENT)
    LEDGER.ok(len(spends) == 1
              and spends[0][1] == authsrv.PLAYER_AGENT_ID,
              "Flare costs 5 and one property 62 goes out for the player",
              f"{spends} -- and it rides 0x00A2, the NO-TARGET float twin, "
              f"which is where all 45 of the corpus's spends are")
    LEDGER.ok(authsrv._f32_of(spends[0][2]) == pools.f32(-0.2),
              "and the value is -(5/25) = -0.2, a FRACTION of the pool",
              f"{authsrv._f32_of(spends[0][2])!r} against f32(-0.2) = "
              f"{pools.f32(-0.2)!r} -- compared in f32 and not in double, "
              f"because that is the difference between 'our model is right' "
              f"and 'our model is close'. OBSERVED: skills 780, 814 and 858 "
              f"all appear at exactly -0.2 with max 25 and cost 5")
    LEDGER.ok(abs(state["energy"].current - 20.0) < 1e-9,
              "and the server's own book agrees with what it just sent",
              f"{state['energy'].current} of 25. The client INTEGRATES its "
              f"copy -- there is no absolute setter, 0 of 13,378 -- so the two "
              f"books have to be two integrations of the same three inputs")

    print("\n6b. and a pool that cannot pay produces NOTHING AT ALL")
    # A FRESH state, not the one above: the first press left a pending cast
    # behind, and asserting "nothing is pending" against a state that already
    # had one would be a check that cannot fail for the reason it claims.
    sent, send, state = fake()
    authsrv.player_energy(state).current = 1.0
    authsrv.handle_skill_press([0, 194, 0, 0], send, state, 0,
                               authsrv.GAME_CMSG_USE_SKILL)
    ops, shaped = refusal_shape(sent)
    LEDGER.ok(shaped and not (set(ops) & cast_cycle_ops()),
              "no E4, no cast animation, no property 62 -- and retail's "
              "refusal batch instead",
              f"{ops}. RE-PINNED 2026-08-21: this said the refusal shape was "
              f"RECONSTRUCTION and retail's answer unobserved. It is OBSERVED "
              f"-- 43 declines of 143 corpus presses, 43 answered, 40 of 40 as "
              f"[0x005D, 0x005E ch7, 0x00E2] in that order. What the check "
              f"really defends is unchanged: a HALF-refusal is wrong under "
              f"every reading, because an E4 with no spend is a free cast. So "
              f"the assertion is no longer 'nothing was sent' but 'exactly the "
              f"refusal batch, and nothing from the cast cycle'")
    LEDGER.ok(not state.get("pending_casts"),
              "and no cast is pending, so no recharge burns for it either",
              f"{state.get('pending_casts')} -- the guard runs before the "
              f"first send and before `cast_busy_until` moves, the same "
              f"discipline `hit_enemy`'s fraction guard follows")
    LEDGER.ok(abs(state["energy"].current - 1.0) < 0.01,
              "and the pool is not debited by the press it refused",
              f"{state['energy'].current} -- the tolerance is the tick of "
              f"regeneration the gate itself integrates (0.99 energy a second "
              f"over the microseconds this takes), not slack in the check: a "
              f"debit would be 5")

    print("\n6c. a ZERO-COST cast sends nothing, which is measured")
    sent2, send2, state2 = fake()
    authsrv.handle_skill_press([0, 1, 0, 0], send2, state2, 0,
                               authsrv.GAME_CMSG_USE_SKILL)
    e4 = [v for op, v, _w in sent2
          if op == authsrv.GAME_SMSG_SKILL_ACTIVATED_BROADCAST]
    LEDGER.ok(len(e4) == 1,
              "Healing Signet (0 energy) casts normally",
              f"{e4}")
    LEDGER.ok(props(sent2, authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_FLOAT,
                    agents.GV_ENERGY_SPENT) == [],
              "and carries NO property 62 -- 44 of 44 in the corpus",
              "`EnergyPool.spend` returns None rather than 0.0 for a free "
              "cast, so this path cannot put a -0.0 on the wire: a value that "
              "reads as a spend in every log we have and that retail never "
              "sends")

    print("\n6d. --no-energy is a real control, not a decoration")
    was = authsrv.ENERGY
    try:
        authsrv.ENERGY = False
        sent3, send3, state3 = fake()
        state3["energy"] = pools.EnergyPool(25, 3)
        state3["energy"].current = 0.0
        authsrv.handle_skill_press([0, 194, 0, 0], send3, state3, 0,
                                   authsrv.GAME_CMSG_USE_SKILL)
        LEDGER.ok(any(op == authsrv.GAME_SMSG_SKILL_ACTIVATED_BROADCAST
                      for op, _v, _w in sent3),
                  "with the flag off an EMPTY pool still casts",
                  "which is exactly the behaviour this server shipped with "
                  "until 2026-08-20 and is what makes the flag a control")
        LEDGER.ok(props(sent3, authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_FLOAT,
                        agents.GV_ENERGY_SPENT) == []
                  and state3["energy"].current == 0.0,
                  "and no property 62 goes out and no pool is touched",
                  f"{state3['energy'].current} -- the gate, the debit, the "
                  f"regeneration and the adrenaline are one switch")
    finally:
        authsrv.ENERGY = was
    LEDGER.ok(authsrv.ENERGY is True,
              "and the DEFAULT is ON, which is what section 6 proved above",
              "a cost that only exists behind a flag is a cost nobody pays. "
              "Sections 6-6c ran against the shipped default")


def section_adrenaline_glue():
    """Adrenaline through the server: swings charge it and a press spends it.

    THE BOOK ONLY. What goes on the wire for it is section 11, and until
    2026-08-21 this docstring said nothing did -- "adrenaline has no opcode in
    `schema/messages.json`, none in GWCA's `Opcodes.h`, and GWCA reads the
    charge out of client MEMORY". All three of those remain true and the
    conclusion was wrong; the catalog carries four unnamed shapes and the
    client has four handlers. What is checked here is unchanged and still
    worth checking on its own: the SERVER's book moves on the events the wiki
    names, and a press it cannot pay for is refused as totally as an energy
    one.
    """
    print("\n7. four swings, one Sever Artery")
    import authsrv

    was_bar = list(authsrv.SKILLBAR)
    try:
        # Sever Artery is not on the default test bar; it is the skill whose
        # RAW cost (100) and displayed cost (4) happen to agree, which is why
        # the neighbouring 317/318/319 are kept alongside it -- their raw costs
        # are 80, 120 and 80 against displayed 4, 5 and 4.
        authsrv.SKILLBAR = [382, 317, 318, 319]
        sent, send, state = fake()
        state["pos"] = (0.0, 0.0)
        state["agents"][7] = {
            "name": "a target", "dead": False, "last_hit": 0.0,
            "health": 5000.0, "max_health": 5000.0, "armor_rating": 60,
            "pos": (10.0, 0.0), "skills": (), "attacks_back": False,
        }
        bar = authsrv.player_adrenaline(state)
        LEDGER.ok(bar.costs == {382: 100, 317: 80, 318: 120, 319: 80},
                  "the pools are built from the bar at the CLIENT's raw units",
                  f"{bar.costs} -- not displayed x 25, which would demand 100 "
                  f"for Battle Rage (317) where GWW's own Notes say it "
                  f"'exactly requires 80 units of adrenaline (3 strikes and 5 "
                  f"units)'")

        authsrv.handle_skill_press([0, 382, 0, 7], send, state, 0,
                                   authsrv.GAME_CMSG_USE_SKILL)
        ops, shaped = refusal_shape(sent)
        LEDGER.ok(shaped and not (set(ops) & cast_cycle_ops()),
                  "pressing it on an EMPTY pool is refused as totally as "
                  "energy, and answered the same way",
                  f"{ops} -- no E4, no animation, no pending cast, and the "
                  f"same three-message answer the energy branch sends. The "
                  f"reason id differs (1960 adrenaline, 1961 energy) and only "
                  f"1960 is observed on the wire")

        for _ in range(4):
            state["agents"][7]["last_hit"] = 0.0     # skip the swing timer
            authsrv.hit_enemy(send, state, 7, 0)
        LEDGER.ok(bar.units[382] == 100 and bar.units[317] == 80,
                  "four landed WEAPON hits are four strikes: 100 units",
                  f"{bar.units} -- WIKI: 25 units per successful weapon hit, "
                  f"and each pool caps at its own cost")
        LEDGER.ok(bar.charged(382) and not bar.charged(318),
                  "so Sever Artery is charged and Defy Pain (120) is not",
                  "which is the whole reason the raw column had to be "
                  "extracted: at displayed x 25 both would read 100")

        sent.clear()
        authsrv.handle_skill_press([0, 382, 0, 7], send, state, 0,
                                   authsrv.GAME_CMSG_USE_SKILL)
        LEDGER.ok(any(op == authsrv.GAME_SMSG_SKILL_ACTIVATED_BROADCAST
                      for op, _v, _w in sent),
                  "now it casts",
                  f"{[hex(op) for op, _v, _w in sent]}")
        LEDGER.ok(bar.units == {382: 0, 317: 55, 318: 75, 319: 55},
                  "its own pool zeroes and every OTHER pool loses one strike",
                  f"{bar.units} -- WIKI, and the cost is paid at USE 'whether "
                  f"or not the skill is interrupted or fails', which is the "
                  f"opposite of the energy spend the corpus shows landing once "
                  f"per COMPLETED cast")

        import agents as _agents
        LEDGER.ok(props(sent, authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_FLOAT,
                        _agents.GV_ENERGY_SPENT) == [],
                  "and NO PROPERTY 62 rides with it -- adrenaline is not energy",
                  "this check used to read 'and NOTHING about the adrenaline "
                  "goes on the wire', on the reasoning that no opcode carried "
                  "it. Four do (0x00CF/0x00D0/0x00D1/0x00D2, section 11), and "
                  "the check only ever looked at property 62 -- so it went on "
                  "passing while its own sentence became false. What it "
                  "actually pins is ArenaNet's own assert "
                  "`!(energyCost && skillData.adrenaline)`: an adrenal skill "
                  "cannot also cost energy, so this burst carries a 0x00D2 "
                  "and no 62")

        print("\n7b. and the thing being hit gains from the damage it takes")
        enemy = state["agents"][7]
        LEDGER.ok(enemy.get("adrenaline_pool") is not None
                  and enemy["adrenaline_bar"] == (),
                  "an agent with no bar carries an INERT pool, not four zeros",
                  f"{enemy.get('adrenaline_bar')} -- `AdrenalinePool` drops "
                  f"every entry whose cost is not positive, so a bar of pure "
                  f"energy skills costs nothing to carry")
    finally:
        authsrv.SKILLBAR = was_bar


def section_death_and_revive():
    """The death batch and the resurrect batch, both OBSERVED.

    Death: property 43 goes to 0.0 in the same instant the death bit goes up --
    the two zero-pip events in the 52-of-52 join are exactly those. Resurrect:
    the death bit clears, 43 goes back to the rate, 52 arrives as exactly 1.0
    and 55 (the health half, which this server already sent) as 1.0 alongside.

    PREDICTION ON RECORD: the client's energy orb sticks at 0 after a revive
    today -- the 2026-08-20 harness frames show it -- because the client's own
    death path zeroes the pool and our revive path has never sent an energy
    property at all. With these out, it must refill. A run falsifies or
    confirms; nothing here can.
    """
    print("\n8. dying and coming back")
    import authsrv
    import agents

    sent, send, state = fake()
    state["player_health"] = 100.0
    authsrv.player_adrenaline(state)
    state["adrenaline"] = pools.AdrenalinePool({317: 80})
    state["adrenaline"].on_hit_landed(0.0)
    authsrv.player_energy(state).current = 12.0
    authsrv.kill_player(send, state, 0, "a test")
    regen = props(sent, authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_FLOAT,
                  authsrv.GV_ENERGY_REGEN)
    LEDGER.ok(len(regen) == 1 and authsrv._f32_of(regen[0][2]) == 0.0,
              "death sends property 43 = 0.0 alongside the death bit",
              f"{regen} -- OBSERVED: the only two property-43 events in the "
              f"corpus that solve to ZERO pips are the two deaths. A corpse "
              f"regenerates nothing, and a client left animating the orb "
              f"upward through a death shows energy arriving on a body that "
              f"cannot spend it")
    LEDGER.ok(not any(state["adrenaline"].units.values()),
              "and every adrenaline pool is emptied",
              "WIKI: all adrenaline is lost upon death. The WIRE half of this "
              "-- one 0x00D0, last in the batch -- is section 11g, and it did "
              "not exist when this line was written: the detail here used to "
              "end 'Nothing on the wire for it, because nothing carries it'")

    print("\n8b. and the resurrect batch puts both back")
    state["player_died_at"] = time.time() - authsrv.PLAYER_REVIVE_AFTER - 1.0
    sent.clear()
    authsrv.player_revive_due(send, state, 0)
    # BOTH HALVES, because the shipped default defers. `REVIVE_REFILL_DEFER` is
    # 0.05 s -- studies/agentprops 1f's experiment, and the reason the pools go
    # out one tick after the death bit clears -- so `player_revive_due` arms a
    # timer and `player_refill_due` is what actually sends. Rewinding the timer
    # rather than sleeping keeps this a state machine test.
    if state.get("player_refill_due_at"):
        state["player_refill_due_at"] = time.time() - 0.01
    authsrv.player_refill_due(send, state, 0)
    gains = props(sent, authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_FLOAT,
                  agents.GV_ENERGY_GAIN)
    regen = props(sent, authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_FLOAT,
                  authsrv.GV_ENERGY_REGEN)
    LEDGER.ok(len(gains) == 1 and authsrv._f32_of(gains[0][2]) == 1.0,
              "property 52 arrives as exactly 1.0 -- a full refill",
              f"{gains} -- OBSERVED n=1, capture 20260817T183756. A full pool "
              f"is a gain of the whole pool, so 1.0 is the FRACTION and not a "
              f"sentinel")
    LEDGER.ok(len(regen) == 1
              and authsrv._f32_of(regen[0][2]) == state["energy"].rate,
              "and property 43 goes back to the agent's own rate",
              f"{authsrv._f32_of(regen[0][2])!r} against "
              f"{state['energy'].rate!r} -- the same f32 the spawn sent, not a "
              f"recomputed double")
    LEDGER.ok(state["energy"].current == state["energy"].maximum,
              "and the server's own pool is full again",
              f"{state['energy'].current}/{state['energy'].maximum}")

    print("\n8c. the DEATH PENALTY shape, which is why the rate is recomputed")
    pool = pools.EnergyPool(25, 4)
    before = pool.rate
    after = pool.set_maximum(22)
    LEDGER.ok(abs(before - 0.052800003439188004) < 1e-12
              and abs(after - 0.06000000238418579) < 1e-12,
              "25 -> 22 at four pips is retail's own 0.0528 -> 0.06",
              f"{before!r} -> {after!r}. OBSERVED n=1: agent 27 of capture "
              f"20260817T183756 died, took the penalty, and had property 43 "
              f"re-sent as the SAME four pips over the NEW denominator. It is "
              f"why `set_maximum` recomputes rather than clamping -- and the "
              f"server has no death penalty yet, so this is the arithmetic "
              f"waiting for the mechanic")


def section_glyph():
    """Glyph of Lesser Energy: the hook is live and the CONTENT is what is short.

    WIKI (GWW, "Glyph of Lesser Energy", infobox as fetched 2026-08-20): "For
    15 seconds, your next 2 Spells cost 10...18 less Energy." The 15 seconds
    are already on the wire -- the client's duration slot for skill 200 is a
    flat 15 and `effects.resolve_duration` sends it. What is missing is the
    amount, and it is missing for a REASON this section pins rather than
    papers over.
    """
    print("\n9. the glyph hook, and the row it is waiting on")
    import authsrv
    import agents

    row = agents.WORLD.get("skill_effect", "200")
    LEDGER.ok(row.get("scale_means") == "Energy",
              "skill 200 is the one content row labelled `Energy`",
              "GWW's own progression-variable name, quoted verbatim in "
              "content/world.toml, which is how every other magnitude in this "
              "server gets its MEANING")
    LEDGER.ok(authsrv.glyph_energy_amount(200, 12) is None,
              "and its AMOUNT is REFUSED, because the scale bit is clear",
              "the client gives 200 scale0 = 10, scale15 = 18 with "
              "skill_arguments = 0. `effects.resolve_duration` already sets "
              "the precedent for that shape: bit clear with EQUAL endpoints is "
              "a flat constant we have witnesses for; bit clear with DIFFERING "
              "endpoints has zero witnesses anywhere and is refused. 10 and 18 "
              "differ. WHAT THE ROW NEEDS is an explicit amount beside "
              "`scale_means` in [skill_effect.200] -- its own provenance "
              "already records that the wiki and the bitfield disagree")

    print("\n9b. with an amount in hand, the discount and the two charges")
    # The amount source is stubbed HERE and only here: the hook, the charge
    # counter and the close are the server's and are what this section is for.
    # Stubbing the number rather than inventing one in content is the honest
    # split -- the code path is testable today, the datum is not ours to make
    # up, and 9a above is the check that says so.
    real = authsrv.glyph_energy_amount
    was_bar = list(authsrv.SKILLBAR)
    try:
        authsrv.glyph_energy_amount = lambda sid, rank: (3 if sid == 200
                                                         else None)
        authsrv.SKILLBAR = [194, 322]
        sent, send, state = fake()
        ep = authsrv.effect_table(state).apply(
            authsrv.PLAYER_AGENT_ID, 200, 12, 15.0, time.time(), type_code=12)
        cost, got_ep, discount = authsrv.energy_cost_for(
            state, authsrv.PLAYER_AGENT_ID, 194, 12)
        LEDGER.ok((cost, discount) == (2, 3) and got_ep is ep,
                  "a live glyph takes 3 off Flare's 5",
                  f"cost {cost}, discount {discount}. The floor is at zero, "
                  f"which is ArenaNet's own (ConstSkill:3769) and matters "
                  f"here: a negative cost would come out the far side as a "
                  f"POSITIVE property 62, a message retail never sends")
        LEDGER.ok(authsrv.energy_cost_for(state, authsrv.PLAYER_AGENT_ID,
                                          322, 12)[0] == 5,
                  "CONTROL: an ATTACK skill at the same 5 energy is NOT cheapened",
                  "Power Attack (322) is type_code 14. GWW says 'your next 2 "
                  "SPELLS', and the three codes taken as spells (4 Hex, 5 "
                  "Spell, 6 Enchantment) are RECONSTRUCTION from the type "
                  "names -- so the boundary is exactly what this control "
                  "guards")

        authsrv.handle_skill_press([0, 194, 0, 0], send, state, 0,
                                   authsrv.GAME_CMSG_USE_SKILL)
        spends = props(sent, authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_FLOAT,
                       agents.GV_ENERGY_SPENT)
        LEDGER.ok(len(spends) == 1
                  and abs(authsrv._f32_of(spends[0][2]) - (-0.08)) < 1e-7,
                  "the first press DEBITS the discounted 2, not the listed 5",
                  f"{authsrv._f32_of(spends[0][2])!r} -- -(2/25) = -0.08 "
                  f"against -(5/25) = -0.2")
        LEDGER.ok(ep["charges"] == 1
                  and not any(op == authsrv.GAME_SMSG_EFFECT_REMOVE
                              for op, _v, _w in sent),
                  "one of the two charges is gone and the episode stays open",
                  f"{ep['charges']} left")
        sent.clear()
        authsrv.handle_skill_press([0, 194, 0, 0], send, state, 0,
                                   authsrv.GAME_CMSG_USE_SKILL)
        LEDGER.ok(ep["charges"] == 0
                  and [v for op, v, _w in sent
                       if op == authsrv.GAME_SMSG_EFFECT_REMOVE]
                  == [[authsrv.PLAYER_AGENT_ID, ep["buff"]]],
                  "and the SECOND press closes it with a real 0x0044",
                  f"{[hex(op) for op, _v, _w in sent]} -- not a silent drop: "
                  f"re-sending or quietly retiring an episode leaves its icon "
                  f"on the client's screen, which is measured (a repeat 0x0042 "
                  f"for a live (agent, skill) is DISCARDED, twice)")
        sent.clear()
        authsrv.handle_skill_press([0, 194, 0, 0], send, state, 0,
                                   authsrv.GAME_CMSG_USE_SKILL)
        spends = props(sent, authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_FLOAT,
                       agents.GV_ENERGY_SPENT)
        LEDGER.ok(len(spends) == 1
                  and abs(authsrv._f32_of(spends[0][2]) - (-0.2)) < 1e-7,
                  "the THIRD press pays the full 5 again",
                  f"{authsrv._f32_of(spends[0][2])!r} -- 'your next 2 Spells', "
                  f"and the third is not one of them")
    finally:
        authsrv.glyph_energy_amount = real
        authsrv.SKILLBAR = was_bar


def section_enemy_gate():
    """The hostile pays too, and nothing goes out for it.

    Property 62 is the observing player's OWN agent's and NOBODY else's: 722
    casts by other agents across the corpus, 579 of them paid, and not one
    spend. Two of that 2x2's four cells are empty, which is what makes it a
    rule. So the enemy's pool is a server-side book, and what it buys is that
    our AI stops casting Restore Condition every 2 seconds forever.
    """
    print("\n10. the enemy's own gate -- a resource rule, not an AI rule")
    import authsrv
    import agents

    def hostile(state, energy):
        agent = {
            "name": "a caster", "dead": False, "attacks_back": True,
            "allegiance": agents.ALLEGIANCE_HOSTILE, "effects": 0,
            "pos": (10.0, 0.0), "health": 100.0, "max_health": 100.0,
            "armor_rating": 60, "attack_speed": 1.75, "last_swing": 0.0,
            "swinging": True, "skills": ((276, 0.75, 2.0),),
            "skill_ready": [0.0], "last_slot": -1,
        }
        state["agents"][9] = agent
        pool = authsrv.agent_energy(agent)
        pool.current = energy
        return agent

    sent, send, state = fake()
    state["pos"] = (0.0, 0.0)
    state["player_health"] = 100.0
    state["player_dead"] = False
    broke = hostile(state, 0.0)
    authsrv.enemy_attack_tick(send, state, 0)
    casts = [v for op, v, _w in sent
             if op == authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_INT
             and v and v[0] == agents.GV_SKILL_ACTIVATED]
    LEDGER.ok(casts == [] and broke.get("cast_lands_at") is None,
              "an agent with 0 energy does not cast its 5-energy heal",
              f"{casts}. Restore Condition costs 5 on a 2.0 s recharge, and "
              f"5 pips over 30 energy is 1.65 a second -- so the POOL paces "
              f"it, which is how retail paces it. That is PLAN.md section 8 "
              f"item 4's heal spam, closed by a resource rule rather than by "
              f"touching the round robin")
    LEDGER.ok(broke["skill_ready"][0] == 0.0,
              "and the slot stays READY, so it retries as the pool fills",
              f"{broke['skill_ready']} -- advancing the cursor here would be "
              f"an AI decision, and `pick_skill` says in its own docstring "
              f"that it is not where those go")

    print("\n10b. CONTROL: the same agent with a full pool casts")
    sent2, send2, state2 = fake()
    state2["pos"] = (0.0, 0.0)
    state2["player_health"] = 100.0
    state2["player_dead"] = False
    rich = hostile(state2, 30.0)
    authsrv.enemy_attack_tick(send2, state2, 0)
    casts = [v for op, v, _w in sent2
             if op == authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_INT
             and v and v[0] == agents.GV_SKILL_ACTIVATED]
    LEDGER.ok(len(casts) == 1 and casts[0][2] == 276,
              "with 30 energy the cast goes out",
              f"{casts} -- so the check above discriminates between two "
              f"outcomes rather than agreeing with whatever it is handed")
    LEDGER.ok(abs(rich["energy_pool"].current - 25.0) < 0.1,
              "and 5 energy is debited from its book",
              f"{rich['energy_pool'].current:.2f} of 30")
    LEDGER.ok(props(sent2, authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_FLOAT,
                    agents.GV_ENERGY_SPENT) == [],
              "with NO property 62 for it -- 0 of 722 in the corpus",
              "579 of those 722 other-agent casts were paid. 'One property 62 "
              "per cast' is the rule this corpus refutes, and it is the rule a "
              "reader who only counted spends would have written")


def adrenaline_msgs(sent, opcode):
    """Every value list sent on one of the four adrenaline opcodes."""
    return [v for op, v, _w in sent if op == opcode]


def section_adrenaline_wire():
    """THE FOUR OPCODES, from the server's own send sites.

    Section 7 above checks that the BOOK moves; this checks that the client is
    told. Until 2026-08-21 nothing was: `pools.py` and `authsrv.py` both said
    "adrenaline is not on the wire at all and that is a finding rather than a
    gap", on the strength of two real absences (no adrenaline opcode in
    `schema/messages.json`, none in GWCA's `Opcodes.h`) and one wrong
    inference. The client has four handlers, the catalog has all four SHAPES
    under placeholder names, and retail sends three of them 724 times across
    the live corpus.

    WHAT IS PINNED HERE that the wire itself decided:

      * the byte lengths, through the REAL codec -- 10, 6, 16, 12, which are
        the client's own `declared_unpack_size`s;
      * SELF-SCOPE. An enemy gaining adrenaline sends NOTHING. 9 of 9 corpus
        connections name exactly one agent, their own;
      * a ZERO-UNIT gain sends nothing, and a real one at the same instant
        does -- the control, so the check discriminates;
      * 0x00D2 lands immediately before the property that names the skill,
        which is measured 39 of 39;
      * 209 has a declaration and NO SEND SITE, checked against the source
        text, because 0 of 724 is what retail does with it;
      * the client's RECHARGE SKIP, with its own control.
    """
    print("\n11. the adrenaline family on the wire")
    import authsrv
    import agents
    from codec import Codec

    print("\n11a. the four shapes, through the real codec")
    codec = Codec()
    SHAPES = (
        (authsrv.AGENT_ADRENALINE_GAIN, [1, 25], 10, "207 {agent, units}"),
        (authsrv.AGENT_ADRENALINE_CLEAR, [1], 6, "208 {agent}"),
        (authsrv.AGENT_ADRENALINE_SET, [1, 382, 0, 100], 16,
         "209 {agent, skill, copy, units}"),
        (authsrv.AGENT_ADRENALINE_SPEND, [1, 382, 0], 12,
         "210 {agent, skill, copy}"),
    )
    widths = []
    for opcode, vals, want, label in SHAPES:
        got = len(codec.encode("GAME_SMSG", opcode, vals))
        widths.append((label, got, want))
    LEDGER.ok(all(got == want for _l, got, want in widths),
              "all four encode to the byte counts the CLIENT declares",
              f"{widths} -- 10/6/16/12 are `declared_unpack_size` in "
              f"schema/messages.json for GAME_SMSG_0207..0210, and this is "
              f"our codec being made to agree with them rather than with our "
              f"own reading of the handlers")
    LEDGER.ok((authsrv.AGENT_ADRENALINE_GAIN, authsrv.AGENT_ADRENALINE_CLEAR,
               authsrv.AGENT_ADRENALINE_SET, authsrv.AGENT_ADRENALINE_SPEND)
              == (pools.OP_ADRENALINE_GAIN, pools.OP_ADRENALINE_CLEAR,
                  pools.OP_ADRENALINE_SET, pools.OP_ADRENALINE_SPEND)
              == (0x00CF, 0x00D0, 0x00D1, 0x00D2),
              "and this file's four numbers agree with `pools.py`'s copies",
              "the same two-copies check section 5 makes for property 43. The "
              "NAMES are ours: GWCA, OpenTyria, Headquarter, GWLP-R, "
              "Py4GW_Reforged and gw-preservation were all searched and none "
              "of them names any of the four, so no derivation-register row "
              "is owed")

    # THREE DECLARATIONS, ONE NAME EACH, AND THEY HAVE TO AGREE. The catalog
    # override was written by the derivation pass off the client's own
    # descriptors; these constants were written by the wiring pass off the
    # house naming rule. Nothing forced them together, so a rename in either
    # place goes red here rather than leaving the server sending an opcode the
    # catalog calls something else.
    import json
    ov = json.load(open(os.path.join(os.path.dirname(HERE), os.pardir,
                                     "schema", "overrides.json"),
                        encoding="utf-8"))
    ov_smsg = ov["channels"]["GAME_SMSG"]
    named = {int(k): v["name"] for k, v in ov_smsg.items()
             if int(k) in (207, 208, 209, 210) and "name" in v}
    LEDGER.ok(named == {207: "AGENT_ADRENALINE_GAIN",
                        208: "AGENT_ADRENALINE_CLEAR",
                        209: "AGENT_ADRENALINE_SET",
                        210: "AGENT_ADRENALINE_SPEND"},
              "and `schema/overrides.json` names the same four the same way",
              f"{named} -- the catalog rows carry the derivation and the "
              f"live counts; these constants carry the sends. They were "
              f"written by two passes with nothing tying them together, and "
              f"the day one is renamed this is what says so")

    src = open(os.path.join(HERE, "authsrv.py"), encoding="utf-8").read()
    LEDGER.ok(src.count("AGENT_ADRENALINE_SET") == 1,
              "209 has a DECLARATION and no send site -- 0 of 724 in retail",
              f"{src.count('AGENT_ADRENALINE_SET')} occurrences in "
              f"authsrv.py. It is a live handler (0x00821B70 writes the "
              f"message's units to both halves of the matched slot), and it "
              f"is the exact shape of energy property 33: implemented, "
              f"reachable, never sent. An absolute setter is the one message "
              f"that HIDES a divergence instead of exposing it, so a later "
              f"session reaching for it to 'resync' is what this counts")

    print("\n11b. a landed WEAPON hit puts one 0x00CF on the wire")
    was_bar = list(authsrv.SKILLBAR)
    try:
        authsrv.SKILLBAR = [382, 317, 318, 319]
        sent, send, state = fake()
        state["pos"] = (0.0, 0.0)
        state["player_health"] = float(agents.PLAYER_HEALTH)
        # THE TARGET IS BUILT SO ITS OWN POOL ACTUALLY MOVES, and 11c is why.
        # A 5,000-health dummy takes 0.1% from a hammer swing, which floors to
        # zero units -- so "no message names the enemy" would hold even if this
        # server DID send one, and the check could not fail for the reason it
        # claims. 100 health puts EVERY roll of the hammer's own 3-5 over the
        # 1% floor (3 to 5 units), which matters because a 300-health target
        # made this check flaky at exactly the low roll; and the adrenal skill
        # gives the agent a pool with something in it to report.
        state["agents"][7] = {
            "name": "a target", "dead": False, "last_hit": 0.0,
            "health": 100.0, "max_health": 100.0, "armor_rating": 60,
            "pos": (10.0, 0.0), "skills": ((382, 0.0, 0.0),),
            "attacks_back": False,
        }
        bar = authsrv.player_adrenaline(state)
        authsrv.hit_enemy(send, state, 7, 0)
        gains = adrenaline_msgs(sent, authsrv.AGENT_ADRENALINE_GAIN)
        LEDGER.ok(gains == [[authsrv.PLAYER_AGENT_ID, 25]],
                  "one strike, as [player, 25] -- RAW UNITS, not a fraction",
                  f"{gains}. 631 of retail's 663 gains carry exactly 25, and "
                  f"the client ADDS the message's number to each slot "
                  f"(`add eax,[ebp+0xc]` at 0x008219E1) -- so the wire value "
                  f"and the granted value have to be one integer")
        LEDGER.ok(bar.units[382] == 25,
                  "and the server's own book took the same 25",
                  f"{bar.units} -- two integrations of one event stream, "
                  f"because nothing resyncs them: 209 is the absolute setter "
                  f"and retail sends it 0 times in 724")

        print("\n11c. and the ENEMY's own gain sends NOTHING -- 9 of 9")
        enemy = state["agents"][7]
        enemy_units = dict(enemy["adrenaline_pool"].units)
        named = [v for op, v, _w in sent
                 if op in (authsrv.AGENT_ADRENALINE_GAIN,
                           authsrv.AGENT_ADRENALINE_CLEAR,
                           authsrv.AGENT_ADRENALINE_SET,
                           authsrv.AGENT_ADRENALINE_SPEND)
                 and v[0] == 7]
        LEDGER.ok(any(enemy_units.values()) and named == [],
                  "the hostile's pool MOVED and not one message names it",
                  f"the enemy's book is {enemy_units} and the adrenaline "
                  f"messages naming agent 7 are {named}. Both halves matter: a "
                  f"target too big to earn a unit would make the silence "
                  f"vacuous, which is what the first cut of this check was. "
                  f"Every connection in the corpus carrying a 0x00CF names "
                  f"exactly ONE agent id, and it equals that connection's own "
                  f"opcode-218 SKILLBAR_UPDATE agent -- so sending an enemy's "
                  f"adrenaline would be inventing traffic, the same way a "
                  f"property 62 for another agent would (0 of 722)")

        print("\n11d. a sub-1% hit sends nothing, and the control at 1% does")
        sent.clear()
        # THE RULE IS ROUND, NOT FLOOR -- measured 2026-08-21 against a wiki
        # that says floored. All 32 sub-25 gains in the live corpus, 31 of
        # which carry a same-batch 0x00A3 naming the gaining agent, join to
        # their own damage: round fits 31/31, floor 14/31, ceil 17/31. The
        # discriminating rows are |pct| 2.500/2.708/2.917/3.542 granting
        # 3/3/3/4 where flooring grants 2/2/2/3.
        #
        # The BOUNDARY moves with it, from 1% to 0.5%, and that half is an
        # EXTRAPOLATION rather than a measurement: the corpus's smallest
        # sample is 2.5%, so nothing observed says what retail does below 1%.
        # Pinned to the rule we can defend, and labelled so nobody reads the
        # 0.4/0.6 pair as measured.
        LEDGER.ok(pools.damage_units(0.004) == 0
                  and pools.damage_units(0.006) == 1
                  and pools.damage_units(0.025) == 3,
                  "round is the rule: 0.4% is nothing, 0.6% is one, 2.5% is "
                  "three (the corpus's own smallest sample)",
                  f"{pools.damage_units(0.004)}, {pools.damage_units(0.006)} "
                  f"and {pools.damage_units(0.025)} -- `damage_units` is a "
                  "module function precisely so the granted integer and the "
                  "wire integer cannot be two different numbers. The 0.4/0.6 "
                  "pair is EXTRAPOLATED (no sub-1% sample exists); 2.5 -> 3 is "
                  "OBSERVED and is one of the four rows that refuted floor")
        authsrv.player_gains_adrenaline(send, state, pools.damage_units(0.004),
                                        time.time(), 0, "a scratch")
        LEDGER.ok(sent == [],
                  "so a scratch puts NOT ONE MESSAGE out",
                  f"{sent} -- an 0x00CF with units 0 leaves the client's "
                  f"`something gained` flag (`mov edi,1`, 0x008219EC) clear "
                  f"and repaints nothing. It is a message that does nothing, "
                  f"and retail has no reason to produce one")
        authsrv.player_gains_adrenaline(send, state, pools.damage_units(0.11),
                                        time.time(), 0, "a real hit")
        LEDGER.ok(adrenaline_msgs(sent, authsrv.AGENT_ADRENALINE_GAIN)
                  == [[authsrv.PLAYER_AGENT_ID, 11]],
                  "CONTROL: 11% of maximum health at the same call site DOES",
                  f"{sent} -- so the silence above is the floor and not a "
                  f"broken call site. 11 is in retail's own sub-25 population "
                  f"{{3:6, 4:12, 5:1, 6:5, 7:1, 8:3, 11:4}}")

        print("\n11e. spending it: 0x00D2 immediately before the naming property")
        sent.clear()
        for _ in range(3):
            state["agents"][7]["last_hit"] = 0.0
            authsrv.hit_enemy(send, state, 7, 0)
        sent.clear()
        authsrv.handle_skill_press([0, 382, 0, 7], send, state, 0,
                                   authsrv.GAME_CMSG_USE_SKILL)
        ops = [op for op, _v, _w in sent]
        spends = adrenaline_msgs(sent, authsrv.AGENT_ADRENALINE_SPEND)
        LEDGER.ok(spends == [[authsrv.PLAYER_AGENT_ID, 382, 0]],
                  "one 0x00D2 as [player, skill, copy]",
                  f"{spends} -- the COPY is echoed from the press's own third "
                  f"field and not assumed: the client's worker matches a slot "
                  f"on (skillId +0x0C, skillCopy +0x10), and +0x10 is filled "
                  f"from SKILLBAR_UPDATE's second array, which this server "
                  f"sends as eight zeros")
        i = ops.index(authsrv.AGENT_ADRENALINE_SPEND)
        after = sent[i + 1]
        LEDGER.ok(after[0] == authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_INT_TARGET
                  and after[1][0] == agents.GV_SKILL_ACTIVATED
                  and after[1][3] == 382,
                  "and the NEXT message is the property naming the same skill",
                  f"{[hex(o) for o in ops]} -- MEASURED 39 of 39: every "
                  f"opcode-210 in the 14 live captures is followed at index "
                  f"+1, same timestamp, by the int property naming that agent "
                  f"and that skill. Zero the other way round. Retail's is "
                  f"property 50 (attack-skill) and ours is 60, which is a "
                  f"pre-existing divergence and not this one")
        LEDGER.ok(props(sent, authsrv.GAME_SMSG_AGENT_PROPERTY_UPDATE_FLOAT,
                        agents.GV_ENERGY_SPENT) == [],
                  "and NO property 62 rides with it, which is ArenaNet's rule",
                  "`!(energyCost && skillData.adrenaline)` asserts at BOTH "
                  "GmCtlSkCard.cpp:409 and GmCtlSkListEntry.cpp:185 -- a "
                  "skill cannot carry both costs. That is why the order of "
                  "0x00D2 against property 62 never has to be decided")

        print("\n11f. the RECHARGE SKIP, which is the client's rule and not ours")
        sent.clear()
        state["pending_casts"] = [{
            "skill_id": 317, "copy": 0, "target": None,
            "e5_at": 0.0, "e3_at": 0.0, "e6_at": time.time() + 30.0,
            "recharge": 30, "e5_sent": True, "e3_sent": True,
        }]
        before = dict(bar.units)
        state["agents"][7]["last_hit"] = 0.0
        authsrv.hit_enemy(send, state, 7, 0)
        LEDGER.ok(bar.units[317] == before[317]
                  and bar.units[318] == before[318] + 25,
                  "Battle Rage is recharging and takes nothing; Defy Pain does",
                  f"{before} -> {bar.units}. `cmp [esi+8],0 / jne` at "
                  f"0x008219C0 skips a slot whose RECHARGE is nonzero before "
                  f"it even reads the skill id. Our pool granted to everything "
                  f"until 2026-08-21, and the divergence would have been "
                  f"PERMANENT -- 209 is the only message that could correct it "
                  f"and retail sends it 0 times in 724")
        LEDGER.ok(adrenaline_msgs(sent, authsrv.AGENT_ADRENALINE_GAIN)
                  == [[authsrv.PLAYER_AGENT_ID, 25]],
                  "and the 0x00CF still goes out in full -- the client skips too",
                  f"{sent[-1]} -- the message carries the COMBAT EVENT, not "
                  f"our bookkeeping. Retail's timeout clears sit 25.00 s after "
                  f"the last 207 ON THE WIRE (15 of 15), so suppressing a "
                  f"grant that every slot refused would move our own clock")
        state["pending_casts"] = []
        state["agents"][7]["last_hit"] = 0.0
        authsrv.hit_enemy(send, state, 7, 0)
        LEDGER.ok(bar.units[317] == before[317] + 25,
                  "CONTROL: with nothing recharging the same slot fills",
                  f"{bar.units} -- so the skip above discriminates rather "
                  f"than agreeing with whatever it is handed. The window is "
                  f"E5 to E6 and not press to E6, because the CLIENT is what "
                  f"is being mirrored and it learns the recharge from 0x00E5")
    finally:
        authsrv.SKILLBAR = was_bar

    print("\n11g. death sends one 0x00D0, AFTER the batch that is measured")
    sent, send, state = fake()
    state["player_health"] = 100.0
    authsrv.player_adrenaline(state).on_hit_landed(time.time())
    authsrv.kill_player(send, state, 0, "a test")
    ops = [op for op, _v, _w in sent]
    clears = adrenaline_msgs(sent, authsrv.AGENT_ADRENALINE_CLEAR)
    LEDGER.ok(clears == [[authsrv.PLAYER_AGENT_ID]]
              and ops[-1] == authsrv.AGENT_ADRENALINE_CLEAR,
              "exactly one, and it is the LAST message in the death batch",
              f"{[hex(o) for o in ops]}. THE CORPUS CANNOT RULE ON THE "
              f"POSITION and the cell is EMPTY rather than zero: not one of "
              f"the 9 connections carrying adrenaline ever witnesses its own "
              f"agent dying, so retail's 22 clears being none of them says "
              f"nothing. What IS measured is the death bit -> 0x009C -> "
              f"0x00EE adjacency `test_morale` section 5 pins, so an "
              f"unmeasured message goes after it and never inside it")
    LEDGER.ok(ops[0] == authsrv.GAME_SMSG_AGENT_UPDATE_STATUS
              and not any(o == authsrv.AGENT_ADRENALINE_CLEAR
                          for o in ops[:-1]),
              "and the death bit still goes first, undisturbed",
              f"{[hex(o) for o in ops]} -- the first cut of this change put "
              f"the clear at index 1 and split a sequence read off ArenaNet's "
              f"own capture")
    LEDGER.ok(not any(state["adrenaline"].units.values()),
              "and every pool is emptied behind it",
              "WIKI: all adrenaline is lost upon death, and the client's "
              "0x00D0 worker (0x00821B00) zeroes both halves of all 8 slots. "
              "Sending it is safe under both readings of what the client does "
              "with the death bit: idempotent if it wipes locally, and the "
              "only thing that stops a revive with a full bar if it does not")

    print("\n11h. the 25-second wipe, and its shape is retail's own")
    sent, send, state = fake()
    bar = authsrv.player_adrenaline(state)
    bar.on_hit_landed(time.time() - pools.ADRENALINE_TIMEOUT_S - 1.0)
    authsrv.energy_tick(send, state, 0)
    LEDGER.ok([(op, v) for op, v, _w in sent]
              == [(authsrv.AGENT_ADRENALINE_CLEAR, [authsrv.PLAYER_AGENT_ID])],
              "ONE message and nothing else -- an ISOLATED 0x00D0",
              f"{sent}. That is exactly what retail's timeout looks like: 15 "
              f"of the 22 corpus clears have nothing around them but world "
              f"ticks, and every one lands 24.973-25.015 s after its agent's "
              f"own last 207-or-210. The wiki said 25 before anyone counted "
              f"one; the two agree to 15 ms")
    sent.clear()
    authsrv.energy_tick(send, state, 0)
    LEDGER.ok(sent == [],
              "and a second tick sends nothing -- it is an event, not a stream",
              f"{sent} -- `AdrenalinePool.tick` drops the clock either way, "
              f"so a wiped bar cannot re-wipe. The energy half of this tick "
              f"stays SILENT under both calls, which is its own measurement: "
              f"52 property-43s in the corpus, none of them a stream")

    print("\n11i. --no-energy takes all four off the wire")
    was = authsrv.ENERGY
    try:
        authsrv.ENERGY = False
        sent, send, state = fake()
        state["pos"] = (0.0, 0.0)
        state["player_health"] = 100.0
        state["agents"][7] = {
            "name": "a target", "dead": False, "last_hit": 0.0,
            "health": 5000.0, "max_health": 5000.0, "armor_rating": 60,
            "pos": (10.0, 0.0), "skills": (), "attacks_back": False,
        }
        authsrv.hit_enemy(send, state, 7, 0)
        authsrv.kill_player(send, state, 0, "a test")
        authsrv.energy_tick(send, state, 0)
        LEDGER.ok(not any(op in (authsrv.AGENT_ADRENALINE_GAIN,
                                 authsrv.AGENT_ADRENALINE_CLEAR,
                                 authsrv.AGENT_ADRENALINE_SET,
                                 authsrv.AGENT_ADRENALINE_SPEND)
                          for op, _v, _w in sent),
                  "a hit, a death and a tick produce none of the four",
                  f"{[hex(op) for op, _v, _w in sent]} -- the gate, the "
                  f"debit, the regeneration, the pools AND now the adrenaline "
                  f"channel are one switch, so a run can say whether what it "
                  f"saw on the skill icons was THIS channel")
    finally:
        authsrv.ENERGY = was
    LEDGER.ok(authsrv.ENERGY is True,
              "and the DEFAULT is ON, which is what 11b-11h ran against",
              "a channel that only exists behind a flag is a channel nobody "
              "watches")


def section_refusal_silent():
    """--refusal-silent is the A/B arm, and an untested arm is not an arm.

    SKILLS-R2 (studies/skills 37) rests entirely on this flag reproducing the
    pre-2026-08-22 server: one press, two runs, one flag apart. If it ever
    stopped suppressing, the A/B would compare two IDENTICAL arms and report
    "no difference" -- which is exactly the shape of the wrong answer that
    session's png stride bug produced, and it would be just as convincing.

    So both directions are asserted here, in-process, with no socket.
    """
    print("\n11j. --refusal-silent suppresses the whole answer, both ways")
    import authsrv

    def refuse_with(silent):
        sent, send, state = fake()
        authsrv.player_energy(state).current = 1.0
        was = authsrv.REFUSAL_SILENT
        authsrv.REFUSAL_SILENT = silent
        try:
            authsrv.handle_skill_press([0, 194, 0, 0], send, state, 0,
                                       authsrv.GAME_CMSG_USE_SKILL)
        finally:
            authsrv.REFUSAL_SILENT = was
        return [op for op, _v, _w in sent]

    loud = refuse_with(False)
    quiet = refuse_with(True)

    LEDGER.ok(quiet == [],
              "with the flag ON a refused press sends NOTHING",
              f"{quiet} -- this is the server we were until 2026-08-22, and "
              f"reproducing it exactly is the flag's whole job. Anything on "
              f"the wire here makes the SKILLS-R2 arms differ by more than "
              f"one thing")

    LEDGER.ok(loud == [authsrv.GAME_SMSG_CHAT_MESSAGE_CORE,
                       authsrv.GAME_SMSG_CHAT_MESSAGE_SERVER,
                       authsrv.GAME_SMSG_SKILL_REFUSED],
              "and with it OFF the full three-message batch goes out",
              f"{loud} -- the DEFAULT, because retail answers 43 of 43 "
              f"declined presses. A flag that defaulted the other way would "
              f"make our own shipped behaviour the experimental arm")

    LEDGER.ok(loud != quiet,
              "so the two arms genuinely differ, which is what makes the A/B "
              "an A/B",
              "stated as its own check rather than left implied: two arms that "
              "silently became identical would still pass both checks above if "
              "either were written loosely, and would read as a clean null")


def main():
    section_quantum()
    section_corpus_oracle()
    section_energy_pool()
    section_adrenaline_pool()
    section_constants()
    section_gate()
    section_adrenaline_glue()
    section_death_and_revive()
    section_glyph()
    section_enemy_gate()
    section_adrenaline_wire()
    section_refusal_silent()

    return LEDGER.verdict()


if __name__ == "__main__":
    sys.exit(main())
